export const GOALSIMULATOR_RETRIEVE_PLANNING_YOUR_RETIREMENT = 'GOALSIMULATOR_RETRIEVE_PLANNING_YOUR_RETIREMENT';
export const GOALSIMULATOR_RETRIEVE_PLANNING_YOUR_RETIREMENT_DONE = 'GOALSIMULATOR_RETRIEVE_PLANNING_YOUR_RETIREMENT_DONE';
export const GOALSIMULATOR_CALCULATE_PLANNING_YOUR_RETIREMENT = 'GOALSIMULATOR_CALCULATE_PLANNING_YOUR_RETIREMENT';
export const GOALSIMULATOR_CALCULATE_PLANNING_YOUR_RETIREMENT_DONE = 'GOALSIMULATOR_CALCULATE_PLANNING_YOUR_RETIREMENT_DONE';
export const GOALSIMULATOR_RECORD_PLANNING_YOUR_RETIREMENT = 'GOALSIMULATOR_RECORD_PLANNING_YOUR_RETIREMENT';
export const GOALSIMULATOR_RECORD_PLANNING_YOUR_RETIREMENT_DONE = 'GOALSIMULATOR_RECORD_PLANNING_YOUR_RETIREMENT_DONE';

export const GOALSIMULATOR_RETRIEVE_PLANNING_YOUR_CHILDREN_FUTURE = 'GOALSIMULATOR_RETRIEVE_PLANNING_YOUR_CHILDREN_FUTURE';
export const GOALSIMULATOR_RETRIEVE_PLANNING_YOUR_CHILDREN_FUTURE_DONE = 'GOALSIMULATOR_RETRIEVE_PLANNING_YOUR_CHILDREN_FUTURE_DONE';
export const GOALSIMULATOR_CALCULATE_PLANNING_YOUR_CHILDREN_FUTURE = 'GOALSIMULATOR_CALCULATE_PLANNING_YOUR_CHILDREN_FUTURE';
export const GOALSIMULATOR_CALCULATE_PLANNING_YOUR_CHILDREN_FUTURE_DONE = 'GOALSIMULATOR_CALCULATE_PLANNING_YOUR_CHILDREN_FUTURE_DONE';
export const GOALSIMULATOR_RECORD_PLANNING_YOUR_CHILDREN_FUTURE = 'GOALSIMULATOR_RECORD_PLANNING_YOUR_CHILDREN_FUTURE';
export const GOALSIMULATOR_RECORD_PLANNING_YOUR_CHILDREN_FUTURE_DONE = 'GOALSIMULATOR_RECORD_PLANNING_YOUR_CHILDREN_FUTURE_DONE';

export const GOALSIMULATOR_RETRIEVE_GROWING_YOUR_WEALTH = 'GOALSIMULATOR_RETRIEVE_GROWING_YOUR_WEALTH';
export const GOALSIMULATOR_RETRIEVE_GROWING_YOUR_WEALTH_DONE = 'GOALSIMULATOR_RETRIEVE_GROWING_YOUR_WEALTH_DONE';
export const GOALSIMULATOR_CALCULATE_GROWING_YOUR_WEALTH = 'GOALSIMULATOR_CALCULATE_GROWING_YOUR_WEALTH';
export const GOALSIMULATOR_CALCULATE_GROWING_YOUR_WEALTH_DONE = 'GOALSIMULATOR_CALCULATE_GROWING_YOUR_WEALTH_DONE';
export const GOALSIMULATOR_RECORD_GROWING_YOUR_WEALTH = 'GOALSIMULATOR_RECORD_GROWING_YOUR_WEALTH';
export const GOALSIMULATOR_RECORD_GROWING_YOUR_WEALTH_DONE = 'GOALSIMULATOR_RECORD_GROWING_YOUR_WEALTH_DONE';

export const GOALSIMULATOR_RETRIEVE_PROTECTION_PLANNING = 'GOALSIMULATOR_RETRIEVE_PROTECTION_PLANNING';
export const GOALSIMULATOR_RETRIEVE_PROTECTION_PLANNING_DONE = 'GOALSIMULATOR_RETRIEVE_PROTECTION_PLANNING_DONE';
export const GOALSIMULATOR_CALCULATE_PROTECTION_PLANNING = 'GOALSIMULATOR_CALCULATE_PROTECTION_PLANNING';
export const GOALSIMULATOR_CALCULATE_PROTECTION_PLANNING_DONE = 'GOALSIMULATOR_CALCULATE_PROTECTION_PLANNING_DONE';
export const GOALSIMULATOR_RECORD_PROTECTION_PLANNING = 'GOALSIMULATOR_RECORD_PROTECTION_PLANNING';
export const GOALSIMULATOR_RECORD_PROTECTION_PLANNING_DONE = 'GOALSIMULATOR_RECORD_PROTECTION_PLANNING_DONE';

export const GOALSIMULATOR_INIT_DATA = 'GOALSIMULATOR_INIT_DATA';
export const GOALSIMULATOR_INIT_DATA_DONE = 'GOALSIMULATOR_INIT_DATA_DONE';

export const GOALSIMULATOR_CALCULATE_RISK_CAPACITY = 'GOALSIMULATOR_CALCULATE_RISK_CAPACITY';
export const GOALSIMULATOR_CALCULATE_RISK_CAPACITY_DONE = 'GOALSIMULATOR_CALCULATE_RISK_CAPACITY_DONE';

// retirement
export const retrievePlanningYourRetirementAct=()=>({
    type: GOALSIMULATOR_RETRIEVE_PLANNING_YOUR_RETIREMENT
})

export const calculatePlanningYourRetirementAct=()=>({
    type: GOALSIMULATOR_CALCULATE_PLANNING_YOUR_RETIREMENT
})

export const recordPlanningYourRetirementAct=()=>({
    type: GOALSIMULATOR_RECORD_PLANNING_YOUR_RETIREMENT
})

// education
export const retrievePlanningYourChildrenFutureAct=()=>({
    type: GOALSIMULATOR_RETRIEVE_PLANNING_YOUR_CHILDREN_FUTURE
})

export const calculatePlanningYourChildrenFutureAct=()=>({
    type: GOALSIMULATOR_CALCULATE_PLANNING_YOUR_CHILDREN_FUTURE
})

export const recordPlanningYourChildrenFuturetAct=()=>({
    type: GOALSIMULATOR_RECORD_PLANNING_YOUR_CHILDREN_FUTURE
})

// group your wealth
export const retrieveGrowingYourWealthAct=()=>({
    type: GOALSIMULATOR_RETRIEVE_GROWING_YOUR_WEALTH
})

export const calculateGrowingYourWealthAct=()=>({
    type: GOALSIMULATOR_CALCULATE_GROWING_YOUR_WEALTH
})

export const recordGrowingYourWealthAct=()=>({
    type: GOALSIMULATOR_RECORD_GROWING_YOUR_WEALTH
})

// protection
export const retrieveProtectionPlanningAct=()=>({
    type: GOALSIMULATOR_RETRIEVE_PROTECTION_PLANNING
})

export const calculateProtectionPlanningAct=()=>({
    type: GOALSIMULATOR_CALCULATE_PROTECTION_PLANNING
})

export const recordProtectionPlanningAct=()=>({
    type: GOALSIMULATOR_RECORD_PROTECTION_PLANNING
})

export const initData=()=>({
    type: GOALSIMULATOR_INIT_DATA
})

// calculate risk capacity
export const calculateRiskCapacityAct=()=>({
    type: GOALSIMULATOR_CALCULATE_RISK_CAPACITY
})

export const updateFieldsDetail=(field)=>({
    type: 'update_fields_detail',
    field
})