export default {
        logon:{
            url:"gateway/authcontroller/logon",
            type:"POST"
        },
       retrieveInvolvedPartyDetailsIndividual:{
			url:"gateway/controller/sfp/involvedPartyMgmtService/retrieveInvolvedPartyDetailsIndividual",
			type:"POST"
		},
        retrieveJointCustomerInformation: {
			url:"gateway/controller/sfp/involvedPartyMgmtService/retrieveJoinCustomer",
			type:"POST"
		},
		retrieveSoleCustomerId:{
			url:"gateway/controller/sfp/involvedPartyMgmtService/retrieveJoinCustomer",
			type:"POST"
		},
        retrieveCustomerListByKey:{
            url:"gateway/controller/sfp/involvedPartyMgmtService/retrieveCustomerListByKey",
			type:"POST"
        },
        recordActivityAuditLog:{
            url:"gateway/controller/sfp/goalSolutionService/recordActivityAuditLog",
			type:"POST"
        },
        retrieveProductSearchResult:{
            url:"gateway/controller/sfp/goalSolutionService/retrieveProductSearchResult",
			type:"POST"
        },
        calculateRiskCapacity:{
            url:"gateway/controller/sfp/goalSolutionService/calculateRiskCapacity",
			type:"POST"
        },
        calculateAggregateAffordabilityRatio:{
            url:"gateway/controller/sfp/goalSolutionService/calculateAggregateAffordabilityRatio",
			type:"POST"
        },
        retrieveGoalSummaryList:{
            url:"gateway/controller/sfp/goalSolutionService/retrieveGoalSummaryList",
			type:"POST"
        },
        retrieveFinancialSituationData:{
            url:"gateway/controller/sfp/customerFinancialInfoService/retrieveFinancialSituationData",
			type:"POST" 
        },
        recordFinancialSituationData:{
            url:"gateway/controller/sfp/customerFinancialInfoService/recordFinancialSituationData",
			type:"POST"
        },
        retrieveCustomerGeneralGoal:{
            url:"gateway/controller/sfp/goalSolutionService/retrieveBaseGoal",
			type:"POST"
        },
        recordCustomerGeneralGoal:{
            url:"gateway/controller/sfp/goalSolutionService/recordBaseGoal",
			type:"POST"
        },
        recordBaseGoal:{
            url:"gateway/controller/sfp/goalSolutionService/recordBaseGoal",
			type:"POST"
        },
        retrieveGoalSolutionDetail:{
            url:"gateway/controller/sfp/goalSolutionService/retrieveGoalSolutionDetail",
			type:"POST"
        },
        recordGoalSolutionDetail:{
            url:"gateway/controller/sfp/goalSolutionService/recordGoalSolutionDetail",
			type:"POST"
        },
        retrieveCustomerFinancialInfo:{
            url:"gateway/controller/sfp/customerFinancialInfoService/retrieveCustomerFinancialInfo",
			type:"POST"
        },
        retrieveGoalPlannerInfo:{
            url:"gateway/controller/sfp/goalSolutionService/retrieveGoalPlannerInfo",
			type:"POST"
        },
        recordGoalPlannerInfo:{
            url:"gateway/controller/sfp/goalSolutionService/recordGoalPlannerInfo",
			type:"POST"
        },
        retrieveMeetingSummaryReportArchive:{
            url:"gateway/controller/sfp/goalSolutionService/retrieveMeetingSummaryReportArchive",
			type:"POST"
        },
        maintainGoalTagging:{
            url:"gateway/controller/sfp/goalSolutionService/maintainGoalTagging",
			type:"POST"
        },
        recordMeetingSummaryReportArchiveAck:{
            url:"gateway/controller/sfp/goalSolutionService/recordMeetingSummaryReportArchiveAck",
			type:"POST"
        },
        recordCustFinPlanInfo:{
            url:"gateway/controller/sfp/customerFinancialInfoService/recordCustomerFinancialInfo",
			type:"POST"
        },
        deleteGoalInformation:{
            url:"gateway/controller/sfp/goalSolutionService/deleteGoalInformation",
			type:"POST"
        },
        retrieveControlAdviceDetail:{
            url:"gateway/controller/sfp/productInfoService/getControlAdvice",
			type:"POST"
        },
        maintainMeetingSummaryReport:{
            url:"gateway/controller/sfp/goalSolutionService/maintainMeetingSummaryReport",
			type:"POST"
        },
        retrieveManagedSolutionDetail:{
            url:"gateway/controller/sfp/goalSolutionService/retrieveManagedSolutionDetail",
			type:"POST"
        },
        reviewInvestments:{
            url:"gateway/controller/sfp/goalSolutionService/reviewInvestments",
			type:"POST"
        },
        retrieveInsuranceQuoteDetails:{
            url:"gateway/controller/sfp/productInfoService/retrieveInsuranceQuoteDetails",
			type:"POST"
        },
        recordInsuranceQuoteDetails:{
            url:"gateway/controller/sfp/productInfoService/recordInsuranceQuoteDetails",
			type:"POST"
        },
        recordQuoteId:{
            url:"gateway/controller/sfp/productInfoService/recordQuoteId",
			type:"POST"
        },
        retrieveGoalProjection:{
            url:"gateway/controller/sfp/goalSolutionService/retrieveGoalProjection",
			type:"POST"
        },
        retrieveOrderPlacement:{
            url:"gateway/controller/sfp/goalSolutionService/retrieveOrderShoppingCart",
			type:"POST"
        },
        createOrderPlacement:{
            url:"gateway/controller/sfp/goalSolutionService/createOrderPlacement",
			type:"POST"
        },
        retrieveTaxOptimizationDetails:{
            url:"gateway/controller/sfp/taxOptimizationService/retrieveTaxOptimizationDetails",
			type:"POST"
        },
        recordTaxOptimizationDetails:{
            url:"gateway/controller/sfp/taxOptimizationService/recordTaxOptimizationDetails",
			type:"POST"
        },
        createPlaceholderAccount:{
            url:"gateway/controller/sfp/taxOptimizationService/createPlaceholderAccount",
			type:"POST"
        },
        retrieveFinancialGoalQuestionnaire:{
            url:"gateway/controller/sfp/goalQuestionnaireService/retrieveFinancialGoalQuestionnaire",
			type:"POST"
        },
        recordFinancialGoalQuestionnaire:{
            url:"gateway/controller/sfp/goalQuestionnaireService/recordFinancialGoalQuestionnaire",
			type:"POST"
        },
        fpsDownloadControlData:{
            url:"gateway/controller/sfp/fpsDownloadControlDataService/fpsDownloadControlData",
			type:"POST"
        },
        retrieveExistingHoldingsContribution:{
            url:"gateway/controller/sfp/goalExistingHoldingContributionService/retrieveGoalExistingHoldingContribution",
			type:"POST"
        },
        recordExistingHoldingsContribution:{
            "url":"gateway/controller/sfp/goalExistingHoldingContributionService/recordGoalExistingHoldingContribution",
			"type":"POST"
        },
        retrieveCustomerAccountList:{
            url:"gateway/controller/sfp/goalSolutionService/retrieveCustomerAccountList",
			type:"POST"
        },
        retrieveQuestionnaireSummary:{
             url:"gateway/controller/sfp/questionnaireService/retrieveQuestionnaireSummary",
             type:"POST"
        },
        calculateQuestionnaireRanking:{
             url:"gateway/controller/sfp/questionnaireService/calculateQuestionnaireRanking",
             type:"POST"
        },
        retrieveQuestionnaireSummary:{
             url:"gateway/controller/sfp/questionnaireService/retrieveQuestionnaireSummary",
             type:"POST"
        },
        maintainQuestionnaireResponseDetail:{
             url:"gateway/controller/sfp/questionnaireService/maintainQuestionnaireResponseDetail",
             type:"POST"
        },
        retrieveQuestionnaireReport:{
             url:"gateway/controller/sfp/questionnaireService/retrieveQuestionnaireReport",
             type:"POST"
        },
        retrieveQuestionnaireResponseDetail:{
             url:"gateway/controller/sfp/questionnaireService/retrieveQuestionnaireResponseDetail",
             type:"POST"
        },
        retrieveQuestionnaire:{
             url:"gateway/controller/sfp/questionnaireService/retrieveQuestionnaire",
             type:"POST"
        },
        downloadQASControlData:{
             url:"gateway/controller/sfp/questionnaireService/retrieveQuestionnaire",
             type:"POST"
        },

        retrieveFinancialSituationReferenceRecordAssets:{
             url:"gateway/controller/sfp/financialSituationReferenceRecordService/assets",
             type:"GET"
        },
        retrieveFinancialSituationReferenceRecordExpenses:{
             url:"gateway/controller/sfp/financialSituationReferenceRecordService/expenses",
             type:"GET"
        },
        retrieveFinancialSituationReferenceRecordIncome:{
             url:"gateway/controller/sfp/financialSituationReferenceRecordService/income",
             type:"GET"
        },
        retrieveFinancialSituationReferenceRecordLiabilities:{
             url:"gateway/controller/sfp/financialSituationReferenceRecordService/liabilities",
             type:"GET"
        },
        enquireFhcSummary:{
             url:"gateway/controller/sfp/finHealthCheckService/enquireFhcSummary",
             type:"POST"
        },
        retrieveFhcDetail:{
             url:"gateway/controller/sfp/finHealthCheckService/retrieveFhcDetail",
             type:"POST"
        },
        updateFhcResult:{
             url:"gateway/controller/sfp/finHealthCheckService/saveFhcResult",
             type:"POST"
        },
        retrieveByCurrency:{
             url:"gateway/controller/sfp/wcsService/retrieveByCurrency",
             type:"POST"
        },
        calculateProtectionPlanning:{
             url:"gateway/controller/sfp/globalSimulatorService/calculateProtection",
             type:"POST"
        },
        recordProtectionPlanning:{
             url:"gateway/controller/sfp/globalSimulatorService/recordProtectionPlanning",
             type:"POST"
        },
        retrieveProtectionPlanning:{
             url:"gateway/controller/sfp/globalSimulatorService/retrieveProtectionPlanning",
             type:"POST"
        },
        calculatePlanningYourRetirement:{
             url:"gateway/controller/sfp/globalSimulatorService/calculatePlanningYourRetirement",
             type:"POST"
        },
        retrievePlanningYourRetirement:{
             url:"gateway/controller/sfp/globalSimulatorService/retrievePlanningYourRetirement",
             type:"POST"
        },
        recordPlanningYourRetirement:{
             url:"gateway/controller/sfp/globalSimulatorService/recordPlanningYourRetirement",
             type:"POST"
        },
        calculateRetirementBenefits:{
             url:"gateway/controller/sfp/globalSimulatorService/calculateRetirementBenefits",
             type:"POST"
        },
        calculateEducation:{
            url:"gateway/controller/sfp/globalSimulatorRestService/education/",
            type:"GET"
        },
        calculateLifeCoverage:{
            url:"gateway/controller/sfp/globalSimulatorRestService/protection/",
            type:"GET"
        },
        calculateCriticalIllness:{
            url:"gateway/controller/sfp/globalSimulatorRestService/protection/",
            type:"GET"
        },
        calculateRetirement:{
            url:"gateway/controller/sfp/globalSimulatorRestService/retirement/",
            type:"GET"
        },
        calculateWealth:{
            url:"gateway/controller/sfp/globalSimulatorRestService/wealth/",
            type:"GET"
        },
        assetConcentrationCalculationGetHolding:{
             url:"gateway/controller/sfp/financialSituationReferenceRetrieveHoldingService/subtotal",
             type:"GET"
        },
         lcsSysemGetStaffID:{
             url:"gateway/controller/sfp/lcsSysemGetStaffID/staffInfor",
             type:"GET"
        },
        retrieveLife400InsuranceDetail:{
             url:"gateway/controller/sfp/financialSituationReferenceRetrieveLifeInsurancePositionService/life400InsuranceDetail",
             type:"GET"
        },
        calculateEducation2:{
            url:"gateway/controller/sfp/globalSimulatorService/calculatePlanningChildrenFuture",
            type:"POST"
        },
        calculateRetirement2:{
            url:"gateway/controller/sfp/globalSimulatorService/calculatePlanningYourRetirement",
            type:"POST"
        },
        calculateLifeCoverage2:{
            url:"gateway/controller/sfp/globalSimulatorService/calculateProtection",
            type:"POST"
        },
        calculateCriticalIllness2:{
            url:"gateway/controller/sfp/globalSimulatorService/calculateProtection",
            type:"POST"
        },
        retrieveQuestionnaireHistoryReport:{
            url:"gateway/controller/sfp/questionnaireService/retrieveQuestionnaireHistoryReport",
            type:"POST"
        },
};
