export const goalSolutionDetailConfig={
      defaultCcy:'HKD',
      //sij
      retrieveGoalSolutionDetail_sij_subServiceIds:['SUMMARY','PIQDTL','NDEVADTL','BUYPURP','INVIND','STATUS'],
      saveSubServiceIds:['SAVNDEVA','SAVBUYPURP','SAVRTQ','SAVLCLFLD','EXPINSQR','SAVPIQ'],
      //insproduct search
      retrieveGoalSolutionDetail_productSearch_subServiceIds:['SUMMARY','STATUS','SPRODLIST','ALTPROD','INVIND','BUYPURP','PIQDTL'],
      //meetingSummary
      retrieveGoalSolutionDetail_meetingSummary_subServiceIds:['SUMMARY','SELDTL','AFFORD','PIQDTL','NOTES','STATUS','DECLARE','CPRODLIST','INVIND','BUYPURP'],
      retrieveGoalSolutionDetail_meetingSummary_requestComment:['GOAL_RSN_RCMD','GOAL_RSN_RCMD_CSDR'],
      //recentPlan      
      retrieveGoalSolutionDetail_recentPlan_subServiceIds:['SUMMARY','SPRODLIST','ALTPROD','INVIND','STATUS'],
      //invGoalSummary 
      retrieveGoalSolutionDetail_invGoalSummary_subServiceIds:['SUMMARY','SELDTL','AFFORD','PIQDTL','NOTES','STATUS','DECLARE','ALTPROD','SPRODLIST','INVIND','EXISTHOL','COMMENT','PRODSNAPSHOT'],
      retrieveGoalSolutionDetail_invGoalSummary_requestComment:['GOAL_RSN_RCMD','GOAL_RSN_RCMD_CSDR','PAS','EXEC_ONLY'],
      //insproductSummary
      retrieveGoalSolutionDetail_GoalSummary_subServiceIds:['SUMMARY','SELDTL','AFFORD','PIQDTL','NOTES','STATUS','DECLARE','CPRODLIST','INVIND','EXISTHOL','COMMENT','PRODSNAPSHOT'],
      retrieveGoalSolutionDetail_GoalSummary_requestComment:['GOAL_RSN_RCMD','GOAL_RSN_RCMD_CSDR'],
      recordGoalSolutionDetail_GoalSummary_subServiceIds:['SAVCOMPLET'],
      
      investorIndicatorKeyList:'INV,AIPI',
      purposeBuyingProductList:'PROD_UDR_OBJ_PROC,PROD_UDR_OBJ_HEL_CAR,PROD_UDR_OBJ_FUR_INC,PROD_UDR_OBJ_SAV,PROD_UDR_OBJ_INV,PROD_UDR_OBJ_OTHER',
      purposeBuyingProduct:{
            PROD_UDR_OBJ_PROC:'Financial protection against adversities ',
            PROD_UDR_OBJ_PROC_E_G:'(e.g. death, accident, disability etc)',
            PROD_UDR_OBJ_HEL_CAR:'Preparation for health care needs ',
            PROD_UDR_OBJ_HEL_CAR_E_G:'(e.g. critical illness, hospitalization etc)',
            PROD_UDR_OBJ_FUR_INC:'Providing regular income in the future ',
            PROD_UDR_OBJ_FUR_INC_E_G:'(e.g. retirement income etc)',
            PROD_UDR_OBJ_SAV:'Saving up for the future ',
            PROD_UDR_OBJ_SAV_E_G:'(e.g. child education, retirement etc)',
            PROD_UDR_OBJ_INV:'Investment',
            PROD_UDR_OBJ_OTHER:'Others, please specify'         
      },
      ins_type_meet_object:'PRE_INSII,PRE_INSIL,PRE_INSP,PRE_INSS,PRE_OTHERS',
      retireAgeKey:'INS_RETRE_AGE',
      localFieldNameCode:'INS_RETRE_AGE',
      additional_questions_retention:'SAVAMT,SAVAMTOPT,TIMFRAMOPT,TIMFRAMVAL,PRE_INSII,PRE_INSIL,PRE_INSP,PRE_INSS,PRE_OTHERS,INSINVPERD,INVPERIOD,INSCONPERD',
      SAVAMTVAL:'SAVAMTVAL',
      SAVAMTCCY:'SAVAMTCCY',
      NO_VALUE:'NO_VALUE',
      WITH_VALUE:'WITH_VALUE',
      INSINVPERD:'INSINVPERD',
      SAVAMT:'SAVAMT',
      SAVAMTOPT:'SAVAMTOPT',
      TIMFRAMOPT:'TIMFRAMOPT',
      TIMFRAMVAL:'TIMFRAMVAL',
      INS_CONTRIBUTE_PERIOD_PIQ_KEY:'INSCONPERD',
      PRE_INSII:'PRE_INSII',
      PRE_INSIL:'PRE_INSIL',
      PRE_INSP:'PRE_INSP',
      PRE_INSS:'PRE_INSS',
      PRE_OTHERS:'PRE_OTHERS',
      // INVPERIOD:'INVPERIOD',
      INSCONPERD:'INSCONPERD',
      question:{
            INSINVPERD:'ANSWER1_1,ANSWER1_2,ANSWER1_3,ANSWER1_4,ANSWER1_5,ANSWER1_6',
            INSCONPERD:'ANSWER_1,ANSWER_2,ANSWER_3,ANSWER_4,ANSWER_5'
      },
      answer:{
            ANSWER1_1:'INS_LST_1',
            ANSWER1_2:'INS_1_5',
            ANSWER1_3:'INS_5_10',
            ANSWER1_4:'INS_10_20',
            ANSWER1_5:'INS_LRT_20',
            ANSWER1_6:'INS_WHLLF',
            ANSWER_1:'1_OR_LESS',
            ANSWER_2:'1_TO_3',
            ANSWER_3:'3_TO_5',
            ANSWER_4:'5_TO_10',
            ANSWER_5:'OVER_10',
      },
      key:{
            INSINVPERD:'L_invPerQues1',
            ANSWER1_1:'L_invPerQues_A11',
            ANSWER1_2:'L_invPerQues_A12',
            ANSWER1_3:'L_invPerQues_A13',
            ANSWER1_4:'L_invPerQues_A14',
            ANSWER1_5:'L_invPerQues_A15',
            ANSWER1_6:'L_invPerQues_A16',
            INSCONPERD:'L_invPerQues',
            ANSWER_1:'L_invPerQues_A1',
            ANSWER_2:'L_invPerQues_A2',
            ANSWER_3:'L_invPerQues_A3',
            ANSWER_4:'L_invPerQues_A4',
            ANSWER_5:'L_invPerQues_A5'
      },
      insuranceNeedkeys:{
            SUPPMFAM:'SUPPMFAM',
            RESERLOT:'RESERLOT',
            ESTAPLAN:'ESTAPLAN',
            OTHERS:'OTHERS',
            PROTCGAP:'PROTCGAP',
            TTLPRTCGAP:'TTLPRTCGAP',
            TOTPRONA:'TOTPRONA',
            TPNMTGEDEB:'TPNMTGEDEB',
            TPNMOINCM:'TPNMOINCM',
            TPNSPTYR:'TPNSPTYR',
            TPNLMPSUM:'TPNLMPSUM',
            TPNINCMREP:'TPNINCMREP'
      },
      label:{  
            L_TargetSavingAmount_Desc:'Do you have a target savings amount to be addressed by life insurance plan(s)?',
            L_TargetSavingAmount_1:'Yes - My target saving amount  is',
            L_TargetSavingAmount_2:'No - I would like to set aside a budget to be used for accumulating saving by life insurance plan(s).',
            L_Timeframe_Desc:'Do you intend to access cash value of your life insurance plan(s) before the end of the target benefit/ protection period?',
            L_Timeframe_1:'Yes - The expected timeframe for accessing the cash value would be',
            L_Timeframe_2:'No',
            INSTIMEFRAME_ANSWER_1:'<= 1 year',
            INSTIMEFRAME_ANSWER_2:'>1 and <=5 years',
            INSTIMEFRAME_ANSWER_3:'>5 and <=10 years',
            INSTIMEFRAME_ANSWER_4:'>10 and <20 years',
            INSTIMEFRAME_ANSWER_5:'>=20 Years',
            INSTIMEFRAME_ANSWER_1_KEY:'TF_LST_1',
            INSTIMEFRAME_ANSWER_2_KEY:'TF_2_5',
            INSTIMEFRAME_ANSWER_3_KEY:'TF_6_10',
            INSTIMEFRAME_ANSWER_4_KEY:'TF_11_20',
            INSTIMEFRAME_ANSWER_5_KEY:'TF_LRT_20', 
            L_ins_type_meet_obj_q:'What type(s) of insurance products you are looking for to meet your objectives? (Select one or more)',
            PRE_INSII:'Insurance product with investment element (Risk born by insurer) ',
            PRE_INSII_E_G:'(Investment decisions and risks borne by insurer e.g. participating policy, universal life insurance)',
            PRE_INSIL:'Insurance product with investment element (Risk born by policyholder) ',
            PRE_INSIL_E_G:'(Investment decisions and risks borne by policyholder e.g. Investment-Linked Assurance Schemes)',
            PRE_INSP:'Pure insurance product (without any savings or investment element) (e.g. term insurance)',
            PRE_INSP_E_G:'(without any savings or investment element e.g. term insurance)',
            PRE_INSS:'Insurance product with savings element ',
            PRE_INSS_E_G:'(with savings but without investment element e.g. non-participating policy)',
            PRE_OTHERS:'Others, Please specify ',
            L_empty_others_ins:'Please specify the other insurance type',
            L_invPerQues1:'What is your target benefit / protection period for insurance policy? ',
            L_invPerQues_A11:'<= 1 year ',
            L_invPerQues_A12:'> 1 and <= 5 years ',
            L_invPerQues_A13:'> 5 and <= 10 years ',
            L_invPerQues_A14:'> 10 and  < 20 years ',
            L_invPerQues_A15:'>= 20 years ',
            L_invPerQues_A16:'Whole of life ',
            L_invPerQues:'For how long are you able and willing to contribute to an insurance policy and / or investment plan ?',
            L_invPerQues_A1:'1 year or less',
            L_invPerQues_A2:'1-3 years',
            L_invPerQues_A3:'3-5 years',
            L_invPerQues_A4:'5-10 years',
            L_invPerQues_A5:'Over 10 years',
            INS_RETRE_AGE_QUE:'Planned retirement age',
            INS_RETRE_AGE_ANS:' Prefill from FHC',
            L_SUPPMFAM:'Exisiting life insurance coverage',
            L_RESERLOT:'Company benefit',
            L_ESTAPLAN:'Life protection gap',
            L_OTHERS:'Other addtional life protection needs to be addressed using insurance plan(s)',
            L_OTHERS_E_G:"'Other addtional life protection needs' is ONLY applicable to the life protection needs that you consider to be addressed using insurance plan(s). If the amount needed has already been included in above sections,please do not include it here to avoid double-counting.",
            L_OTHERS_REMARK:'Others,please specific'
      }
}