export const productSearchConstants={
        /***Allproducts.*/
        FE_PROD_TYPE_CDE_ALL:"FE_ALL",
        /***UTproduct.*/
        FE_PROD_TYPE_CDE_UT:"FE_UT",
        /***INSproduct.*/
        FE_PROD_TYPE_CDE_INS:"FE_INS",
        /***Bondproduct.*/
        FE_PROD_TYPE_CDE_BOND:"FE_BOND",
        /***StructuredProducts.*/
        FE_PROD_TYPE_CDE_SP:"FE_SP",
        /***Depositsproduct.*/
        FE_PROD_TYPE_CDE_DPS:"FE_DPS",
        /***UTtab.*/
        TAB_UT:"TAB_UT",
        /***INStab.*/
        TAB_INS:"TAB_INS",
        /***TAB_INS_NO.*/
        TAB_INS_NO:"TAB_INS_NO",
        /***OTHERtab.*/
        TAB_OTHER:"TAB_OTHER",
        /***UTforProductDisplay.productTypeCode.*/
        UT:"UT",
        /***INSforProductDisplay.productTypeCode.*/
        INS:"INS",
        /***OTHER.*/
        OTHER:"OTHER",
        /***Constanttrue.*/
        TRUE:true,/***Constantfalse.*/
        FALSE:false,/***WPCpaginationorderasc.*/
        WPC_PAGINATION_ORDER_ASCE:"+",
        /***ForWPC,whenrelativepagingisused,codetoindicatetherearemore*recordsintheforwarddirectionbutnotpreviousdirection.*/
        WPC_PAGINATION_ADDITIONAL_FORWARD_RECORDS_CODE:"1",
        /***ForWPC,whenrelativepagingisused,codetoindicatetherearemore*recordsintheforwarddirectionandpreviousdirection.*/
        WPC_PAGINATION_ADDITIONAL_FORWARD_AND_PREVIOUS_RECORDS_CODE:"3",
        /***WPCReferencedatakeyforRiskLevel.*/
        WPC_REF_RISK_LEVEL:"SRCHRSKLVLFP",
        /***WPCReferencedatakeyforTimeToMaturity.*/
        WPC_REF_TIME_TO_MATURITY:"TTMSRCHCRT",
        /***WPCReferencedatakeyforUnderlyingInvestment.*/
        WPC_REF_UNDERLYING_INVESTMENT:"UA",
        /***WPCReferencedatakeyforMarket.*/
        WPC_REF_MARKET:"IVSTMKT",
        /***WPCReferencedatakeyforcurrency.*/
        WPC_REF_CURRENCY:"BASECCY",
        /***WPCReferencedatakeyforCharacteristics.*/
        WPC_REF_CHARACTERISTICS:"IVSTCHRSRCHCRT",
        /***WPCReferencedatakeyforMinimumInvestmentAmount.*/
        WPC_REF_MIN_INVEST_AMOUNT:"IVSTMINAMT",
        /***WPCReferencedatakeyforFundHouse.*/
        WPC_REF_FUND_HOUSE:"FH",
        /***WPCReferencedatakeyforFundCategory.*/
        WPC_REF_PRODSUBTP:"PRODSUBTP",
        /***WPCReferencedatakeyforShareClass.*/
        WPC_REF_SHARE_CLASS:"INHANDOPTCDE",
        /***WPCReferencedatakeyforFundClass.*/
        WPC_REF_FUND_CLASS:"FC",
        /***WPCReferencedatakeyforOnshore/Offshore.*/
        WPC_REF_ONSHORE_OFFSHORE:"PRDSHRLOCCDE",
        /***WPCReferencedatakeyforperiodProductCode(forTenorfield).*/
        WPC_REF_TENOR:"TEN",
        /***WPCReferencedataparenttypeforPRODTYP.*/
        WPC_REF_PARENT_TYPE_PRODTYP:"PRODTYP",
        /***WPCReferencedatakeyforAssetClass.*/
        WPC_REF_ASSET_CLASS:"ASETVOLCLSGRP",
        /***Thekeyforsearchtype.*/
        KEY_SEARCH_TYPE:"KEY_SEARCH_TYPE",
        /***Commonsearchindicator.*/
        COMMON_SEARCH:"COMMON_SEARCH",
        /***INDEX_PREFIX.*/
        PARENTHESES_LEFT:" ( ",
        /***INDEX_PREFIX.*/
        PARENTHESES_RIGHT:" ) ",
        /***INDEX_PREFIX.*/
        INDEX_PREFIX:" {",
        /***INDEX_SUFFIX.*/
        INDEX_SUFFIX:"} ",
        /***AND_RALATION.*/
        AND_RALATION:" AND ",
        /***AND_RALATION.*/
        OR_RALATION:" OR ",
        /***FILTER_CRITERIA_TAB_FORMULA.*/
        FILTER_CRITERIA_TAB_FORMULA:"formula",
        /***FILTER_CRITERIA_TAB_CRITERIAS.*/
        FILTER_CRITERIA_TAB_CRITERIAS:"criterias",
        /***FILTER_CRITERIA_TAB_CRITERIA_KEY.*/
        FILTER_CRITERIA_TAB_CRITERIA_KEY:"key",
        /***FILTER_CRITERIA_TAB_CRITERIA_VALUES.*/
        FILTER_CRITERIA_TAB_CRITERIA_VALUES:"values",
        /***FILTER_CRITERIA_TAB_CRITERIA_INDEX.*/
        FILTER_CRITERIA_TAB_CRITERIA_INDEX:"index",
        /***FILTER_CRITERIA_TAB_CRITERIA_KEY_TYPE.*/
        FILTER_CRITERIA_TAB_CRITERIA_KEY_TYPE:"keyType",
        /***FILTER_CRITERIA_TAB_CRITERIA_VALUE_TYPE.*/
        FILTER_CRITERIA_TAB_CRITERIA_VALUE_TYPE:"valueType",
        /***FILTER_CRITERIA_TAB_CRITERIA_OPERATOR.*/
        FILTER_CRITERIA_TAB_CRITERIA_OPERATOR:"operator",
        /***VALUE_OR.*/
        VALUE_OR:"|",
        /***TheUNCLARIFIED.*/
        UNCLARIFIED:"U",
        /***TheWARN_UNCLARIFIED_ELIGIBILITY.*/
        WARN_UNCLARIFIED_ELIGIBILITY:"WARN_UNCLARIFIED_ELIGIBILITY",
        /***TheTAB_FOR_PRODUCT_TYPE_PREFIX.*/
        TAB_FOR_PRODUCT_TYPE_PREFIX:"tab_for_product_type",
        /***TheWPC_PRODUCT_TYPE_CODES_PREFIX.*/
        WPC_PRODUCT_TYPE_CODES_PREFIX:"wpc_product_type_codes",
        /***TheClassCriteriaKey.*/
        CriteriaKey:{
            ALLOW_BUY_PROD_IND:"ALLOW_BUY_PROD_IND",
            /***SearchCriteriakey-ProductType.*/
            PROD_TYPE_CDE:"PROD_TYPE_CDE",
            /***SearchCriteriakey-RiskLevel.*/
            RISK_LVL_CDE:"RISK_LVL_CDE",
            /***SearchCriteriakey-TimeToMaturity.*/
            TERM_REMAIN_DAY_CNT:"TERM_REMAIN_DAY_CNT",
            /***SearchCriteriakey-UnderlyingInvestment.*/
            ASET_UNDL_CDE:"ASET_UNDL_CDE",
            /***SearchCriteriakey-Market.*/
            MKT_INVST_CDE:"MKT_INVST_CDE",
            /***SearchCriteriakey-Currency.*/
            CCY_PROD_CDE:"CCY_PROD_CDE",
            /***SearchCriteriakey-Characteristics.*/
            INCM_CHAR_PROD_IND:"INCM_CHAR_PROD_IND",
            /**TheConstantCPTL_GURNT_PROD_IND.*/
            CPTL_GURNT_PROD_IND:"CPTL_GURNT_PROD_IND",
            /**TheConstantYIELD_ENHN_PROD_IND.*/
            YIELD_ENHN_PROD_IND:"YIELD_ENHN_PROD_IND",
            /**TheConstantGRWTH_CHAR_PROD_IND.*/
            GRWTH_CHAR_PROD_IND:"GRWTH_CHAR_PROD_IND",
            /***SearchCriteriakey-MinimumInvestmentAmount.*/
            INVST_INIT_MIN_AMT:"INVST_INIT_MIN_AMT",
            /***SearchCriteriakey-Productcode.*/
            PROD_CDE_PROD_CDE_ALT_CLASS_CDE_OR_PROD_ALT_NUM:"ALT_CLASS_CDE|PROD_ALT_NUM",
            /**TheConstantPROD_CDE_CTRY_PROD_TRADE_1_CDE.*/
            PROD_CDE_CTRY_PROD_TRADE_1_CDE:"CTRY_PROD_TRADE_1_CDE",
            /***SearchCriteriakey-ProductName.*/
            PROD_NAME:"PROD_NAME",
            /**TheConstantPROD_PLL_NAME.*/
            PROD_PLL_NAME:"PROD_PLL_NAME",
            /**TheConstantPROD_SLL_NAME.*/
            PROD_SLL_NAME:"PROD_SLL_NAME",
            /***SearchCriteriakey-HSBCHighlight.*/
            HSBC_HIGHLIGHT:"LIST_PROD_TYPE|LIST_PROD_CDE",
            /***SearchCriteriakey-HSBCWorldwideFundsService.*/
            HSBC_WORLDWIDE_FUNDS_SERVICE:"LIST_PROD_TYPE|LIST_PROD_CDE",
            /***SearchCriteriakey-FundHouse.*/
            FUND_HOUSE_CDE:"FUND_HOUSE_CDE",
            /***SearchCriteriakey-FundCategory.*/
            FUND_CATEGORY_PROD_SUBTP_CDE:"PROD_SUBTP_CDE",
            /***SearchCriteriakey-FundCode.*/
            FUND_CODE_PROD_CDE_ALT_CLASS_CDE_OR_PROD_ALT_NUM:"ALT_CLASS_CDE|PROD_ALT_NUM",
            /**TheConstantFUND_CODE_CTRY_PROD_TRADE_1_CDE.*/
            FUND_CODE_CTRY_PROD_TRADE_1_CDE:"CTRY_PROD_TRADE_1_CDE",
            /***SearchCriteriakey-Topperformer.*/
            TOP_PERFM_PROD_IND:"TOP_PERFM_PROD_IND",
            /***SearchCriteriakey-Bestsellers.*/
            TOP_SELL_PROD_IND:"TOP_SELL_PROD_IND",
            /***SearchCriteriakey-Currencyclass.*/
            CCY_PROD_TRADE_CDE:"CCY_PROD_TRADE_CDE",
            /***SearchCriteriakey-ShareClass.*/
            INCM_HANDL_OPT_CDE:"INCM_HANDL_OPT_CDE",
            /***SearchCriteriakey-Fundclass.*/
            FUND_CLASS_CDE:"FUND_CLASS_CDE",
            /***SearchCriteriakey-EligibilityforRegularSavingsPlan.*/
            ALLOW_SELL_MIP_PROD_IND:"ALLOW_SELL_MIP_PROD_IND",
            /***SearchCriteriakey-Onshore/Offshore.*/
            PROD_SHORE_LOC_CDE:"PROD_SHORE_LOC_CDE",
            /***SearchCriteriakey-ISA/nonISA.*/
            PROD_TAX_FREE_WRAP_ACT_STA_CDE:"PROD_TAX_FREE_WRAP_ACT_STA_CDE",
            /***SearchCriteriakey-InsuranceProductType.*/
            INSURANCE_PRODUCT_TYPE_PROD_SUBTP_CDE:"PROD_SUBTP_CDE",
            /***SearchCriteriakey-RequiredSegments.*/
            REQ_SEG:"REQ_SEG",
            /***SearchCriteriakey-AssetClass.*/
            ASSET_CLASS_CDE:"ASET_VOLTL_CLASS_MAJR_PRNT_CDE",
            CriteriaKey:{}
        },
        CriteriaKeyType:{
            GENL:"GENL",
            /***SearchCriteriakeyType-EXFD.*/
            EXFD:"EXFD",
            /***SearchCriteriakeyType-UDAS.*/
            UDAS:"UDAS",
            /***SearchCriteriakeyType-PDSL.*/
            PDSL:"PDSL",
            /***SearchCriteriakeyType-UNTR.*/
            UNTR:"UNTR",
            /***SearchCriteriakeyType-CPTC.*/
            CPTC:"CPTC",
            /***SearchCriteriakeyType-PDAL.*/
            PDAL:"PDAL",
            /***Privateconstructortoensurenosub-classingorinstantiation.*/
            CriteriaKeyType:{}
        },

        CriteriaOperator:{
            EQUAL:"=",
            /***SearchCriteriaoperator-RANGE.*/
            RANGE:"RANGE",
            /***SearchCriteriaoperator-Lessthanorequal.*/
            LESS_THAN_OR_EQUAL:"<=",
            /***SearchCriteriaoperator-LIKE.*/
            LIKE:"LIKE",
            /***SearchCriteriaoperator-ISNOT.*/
            IS_NOT:"ISNOT",
            /***Privateconstructortoensurenosub-classingorinstantiation.*/
            CriteriaOperator:{}
        },
        CriteriaValueType:{
            TEXT:"TEXT",
            /***SearchCriteriavalueType-DATVAL.*/
            DATVAL:"DATVAL",
            /***SearchCriteriavalueType-OTHER.*/
            OTHER:"OTHER",
            /***SearchCriteriavalueType-REFDAT.*/
            REFDAT:"REFDAT",
            /***Privateconstructortoensurenosub-classingorinstantiation.*/
            CriteriaValueType:{}
        },
        CriteriaValue:{
            N:"N",
            /***SearchCriteriavalue-Y.*/
            Y:"Y",
            /***SearchCriteriavalue-SLT|SLT_1.*/
            SLT_SLT_1:"SLT|SLT_1",
            /***SearchCriteriavalue-SLT|SLT_2.*/
            SLT_SLT_2:"SLT|SLT_2",
            /***SearchCriteriavalue-NULL.*/
            NULL:"NULL",
            /***SearchCriteriavalue-ONE.*/
            ONE:"1",
            /***SearchCriteriavalue-TWO.*/
            TWO:"2",
            /***SearchCriteriavalue-THREE.*/
            THREE:"3",
            /***SearchCriteriavalue-M.*/
            M:"M",
            /***SearchCriteriavalue-PRODID.*/
            PRODID:"PRODID",
            /***SearchCriteriavalue-PRODINFO.*/
            PRODINFO:"PRODINFO",
            /***SearchCriteriavalue-PRODPRICE.*/
            PRODPRICE:"PRODPRICE",
            /***SearchCriteriavalue-UTPRDINFO.*/
            UTPRDINFO:"UTPRDINFO",
            /***SearchCriteriavalue-SHRTLIST.UseforgettingFeatureCodefrom*WPC.e.g.HSBCWorldwideFundsService.*/
            SHRTLIST:"SHRTLIST",
            /***Privateconstructortoensurenosub-classingorinstantiation.*/
            CriteriaValue:{}
        },
        CriteriaKeyRelationship:{
            AND:"AND",
            /***Privateconstructortoensurenosub-classingorinstantiation.*/
            CriteriaKeyRelationship:{}
        },
        RefCodeCharacteristics:{
            CDE_INCOME:"I",
            /***CapitalProtection.*/
            CDE_CAPITAL_PROTECTION:"C",
            /***YieldEnhancement.*/
            CDE_YIELD_ENHANCEMENT:"Y",
            /***CapitalGain.*/
            CDE_CAPITAL_GAIN:"G",
            /***Privateconstructortoensurenosub-classingorinstantiation.*/
            RefCodeCharacteristics:{}
        },
            ProdSearchTechFieldVal:{
            G:"G",
            /***ifFEpassthevalue'O'toSFP,whichmeansOthers,andSFPwill*trytocallWPCwiththenewmessage.*/
            O:"O",
            /***ifFEpassthevalue'N'toSFP,whichmeansproductspecific*search,andSFPwilltrytocallWPConetime.*/
            N:"N",
            /***Privateconstructortoensurenosub-classingorinstantiation.*/
            ProdSearchTechFieldVal:{}
        },
        FUND_ISA:"ISA",
        /***NONISA.*/
        FUND_NONISA:"NONISA",
        /***UsetofilterWPC'sProductId.ProductCodeAlternativeClassCode.*/
        WPC_FILTER_PROD_CDE_ALTERNATIVE_CLASS_CDE:"M",
        /***EMPTY_STRING.*/
        EMPTY_STRING:"",
        /***Numberofrecordsperpage.*/
        NUM_RECORDS_PER_PAGE:"number_of_records_per_page",
        /***TheDEFAULT_ITEMS_PER_PAGE_INT_VALUE.*/
        publicstaticfinalintDEFAULT_ITEMS_PER_PAGE_INT_VALUE:10,/***TheDEFAULT_ITEMS_PER_PAGE.*/
        DEFAULT_ITEMS_PER_PAGE:"DEFAULT_ITEMS_PER_PAGE",
        /***TherefDataSetITEMS_PER_PAGE.*/
        ITEMS_PER_PAGE:"ITEMS_PER_PAGE",
        /***TheDEFAULT_ACTIVE_TAB_NAME.*/
        DEFAULT_ACTIVE_TAB_NAME:"DEFAULT_ACTIVE_TAB_NAME",
        /***ThePARAM_ACTIVE_TAB_NAME.*/
        PARAM_ACTIVE_TAB_NAME:"ACTIVE_TAB_NAME",
        /***TheFORCE_SEARCH.*/
        FORCE_SEARCH:"FORCE_SEARCH",
        /***TheREMOVE_DISCUSSED_PRODUCT.*/
        REMOVE_DISCUSSED_PRODUCT:"removeDiscussedProduct",
        /***TheADD_DISCUSSED_PRODUCT.*/
        ADD_DISCUSSED_PRODUCT:"addDiscussedProduct",
        /***TheDISABLE_DISCUSSED_PRODUCT_FEATURE.*/
        DISABLE_DISCUSSED_PRODUCT_FEATURE:"disableDiscussedProductFeature",
        /***keyforRetrieveProductSearchResultResponseinrequestscope.*/
        PRODUCT_SEARCH_RESULT_RESPONSE:"RETRIEVE_PRODUCT_SEARCH_RESULT_RESPONSE",
        /***theconstantofrisklevelprefix.*/
        RISK_LEVEL_PREFIX:"product_risk_level_",
        /**AI/PIIndicator.*/
        AIPIIND:"AIPIIND",
        /**lastmonthtopperformers*/
        TOPPERFM:"TOPPERFM",
        /***ConstantYESforconfiguration.*/
        YES:"Y",
        /***ConstantNOTforconfiguration.*/
        NOT:"N",
        SFPB:"SFPB",
        /***'SFPB'forbranchchanneland'SFPI'forinternetchannelas*'BusinessProcessCode'forthosemessagerelatedtoWPC.*/
        SFPI:"SFPI",
        /***ELIGIBILITY_PVC.*/
        ELIGIBILITY_PVC:"PVC",
        /**HIGH_ASSET_CONCENTRATION_CODE_KEY.*/
        HIGH_ASSET_CONCENTRATION_CODE_KEY:"HIGH_ASSET_CONCENTRATION_CODE",
        /***TheClassSorting.*/
        Sorting:{/***Productname.*/
            PROD_NAME:"A.PROD_NAME",
            /***ProductTypeCode.*/
            PROD_TYPE_CDE:"A.PROD_TYPE_CDE",
            
            ASC:"+",
            DESC:"-",
            /***DESC.*/
            /***Privateconstructortoensurenosub-classingorinstantiation.*/
            Sorting:{}
        },
        ProductSearchConstants:{},
        PRODUCT_SELEC_METHOD_CODE_EXEC_ONLY:"E",
        /**TheConstantSHOW_SPN_SUITABLE_PRODS.*/
        SHOW_SPN_SUITABLE_PRODS:"suitable_products_nsp",
        /**TheConstantSHOW_EO_SUITABLE_PRODS.*/
        SHOW_EO_SUITABLE_PRODS:"suitable_products_eo",
        /**TheConstantSHOW_NSP_SUITABLE_PRODS.*/
        SHOW_NSP_SUITABLE_PRODS:"suitable_products_nsp",
        /**TheConstantENABLE_SUITABLE_PRODS_FILTER.*/
        ENABLE_SUITABLE_PRODS_FILTER:"enable_suitable_product_filter",
        /**TheConstantFLOW_SHORT_NAME_NSP.*/
        FLOW_SHORT_NAME_NSP:"NSP",
        /**TheConstantFLOW_SHORT_NAME_EO.*/
        FLOW_SHORT_NAME_EO:"EO",
        /**TheConstantFLOW_SHORT_NAME_SPN.*/
        FLOW_SHORT_NAME_SPN:"SPN",
        /***SHORTLIST_PROD_FEATURE_ON.*/
        SHORTLIST_PROD_FEATURE_ON:"search_shortlist_prod_only_feature",
        /**SHORTLIST_ONLY_REQUEST_MODE.*/
        SHORTLIST_ONLY_REQUEST_MODE:"SHORTLIST_PRODUCT",
        /**INSURANCE_ONLY_REQUEST_MODE.*/
        INSURANCE_ONLY_REQUEST_MODE:"INSURANCE_ONLY",
        /**TAB_PRODUCT_COUNT_REQUEST_MODE.*/
        TAB_PRODUCT_COUNT_REQUEST_MODE:"TAB_PRODUCT_COUNT",
        /**COUNT_SEARCH_ENABLE.*/
        COUNT_SEARCH_ENABLE:"COUNT_SEARCH_ENABLE",
        /**TAB_ALL_FOR_PROD_SELECTION.*/
        TAB_ALL_FOR_PROD_SELECTION:"TAB_ALL_FOR_PROD_SELECTION",
        /**TAB_ALL_(NOINS)FOR_PROD_SELECTION.*/
        TAB_ALL_FOR_PROD_SELECTION_NO_INS:"TAB_ALL_FOR_PROD_SELECTION_NO_INS",
        /**HAVE_SEARCH_COUNTS.*/
        HAVE_SEARCH_COUNTS:"HAVE_SEARCH_COUNTS",
        /**TheConstantNOT_SEARCH_CLICK.*/
        NOT_SEARCH_CLICK:"NOT_SEARCH_CLICK",
        /**STRING_TRUE.*/
        STRING_TRUE:"true",
        /**TheConstantISRESET_KEY.*/
        ISRESET_KEY:"isReset",
        /**FUND_CLASS_GROUP_KEY*.*/
        FUND_CLASS_GROUP_KEY:"fundClsGrpCde",
        /**maximumAllowAge**/
        MAXIMUM_ALLOW_AGE:"maximumAllowAge",
        /**minimumAllowAge**/
        MINMUM_ALLOW_AGE:"minimumAllowAge",
        /**FUND_CLASS_GROUP_NAME*.*/
        FUND_CLASS_GROUP_NAME:"FUND_CLASS_GROUP_NAME",
        /**TheConstantCHECK_SELECTED_RISK_LEVEL.*/
        CHECK_SELECTED_RISK_LEVEL:"CHECK_SELECTED_RISK_LEVEL",
        /**TheConstantWARN_MSG_HIGHER_RISK_LEVEL.*/
        WARN_MSG_HIGHER_RISK_LEVEL:"WARN_MSG_HIGHER_RISK_LEVEL",
        /**TheConstantWARN_MSG_HIGHER_RISK_LEVEL_DEFAULT.*/
        WARN_MSG_HIGHER_RISK_LEVEL_DEFAULT:"Pleasenotethatyou'veselectedahigherrisklevelthanyourriskcapacitye.",
        /**Theproductlinagenumber.**/
        PRD_LINK_NUM:"PRD_LINK_NUM",
        /**Theproducthierarchycode.**/
        PRD_HIER_CDE:"PRD_HIER_CDE",
        /**Theproductrisk.**/
        RISK:"RISK",
        /**Theproductsubtype.**/
        PRD_SUBTYP:"PRD_SUBTYP",
        /**TheConstantPARAM_SHOW_PVC_OVERLAY_KEY.*/
        PARAM_SHOW_PVC_OVERLAY_KEY:"PARAM_SHOW_PVC_OVERLAY_KEY",
        /**TheConstantPARAM_CONFIG_RISK_LEVEL_KEY.*/
        PARAM_CONFIG_RISK_LEVEL_KEY:"PARAM_CONFIG_RISK_LEVEL_KEY",
        INS_TYPE_PIQ_KEY:"INSTYPE",
        INS_CONTRIBUTE_PERIOD_PIQ_KEY:"INSCONPERD",
        DISABLE_SEARCH_WO_INS_PIQ:"DISABLE_SEARCH_WO_INS_PIQ",
        ERROR_MSG_INS_TYPE_OTHER:"ERROR_MSG_INS_TYPE_OTHER",
        /**IND_HIGHYIELDBONDFUND*.*/
        IND_HIGHYIELDBONDFUND:"highYieldBondFundInd",
        /**IND_FUNDDERIVTEKNOWLDGREQUIREDIND*.*/
        IND_FUNDDERIVTEKNOWLDGREQUIREDIND:"fundDerivteKnowldgRequiredInd",
        /**IND_HIGHYIELDBONDIND*.*/
        IND_HIGHYIELDBONDIND:"highYieldBondInd",
        INS_RETRE_AGE:"INS_RETRE_AGE",
        PARAM_SHOW_INSURANCEREMIND_OVERLAY_KEY:"PARAM_SHOW_INSURANCEREMIND_OVERLAY",
        SAVE_AMT:"SAVAMT",
        SAVE_AMT_IND:"SAVAMTOPT",
        SAVE_AMT_VAL:"SAVAMTVAL",
        SAVE_AMT_CCY:"SAVAMTCCY",
        TIMFRAMOPT:"TIMFRAMOPT",
        TIMFRAMVAL:"TIMFRAMVAL",
        NO_VALUE:"NO_VALUE",
        WITH_VALUE:"WITH_VALUE",
        NOT_SELECT:"NOT_SELECT",
        CUSTOMEROBJECTIVE_LIST_KEY:"customerObjectiveList",
        SHORT_FALL:"SHORT_FALL",
        INSINVPERD:"INSINVPERD",
        /*FundCompare*/
        ADD_FUND_COMPARE_PRODUCT:"addFundCompareProduct",
        REMOVE_FUND_COMPARE_PRODUCT:"removeFundCompareProduct",
        INVESTMENT_PREFERENCE_TYPE_CODE_RC:"RC",
        GOAL_LOCAL_FIELD_KEY_GOAL_RISK_LEVEL:"GOAL_RISK_LEVEL",
        GOAL_LOCAL_FIELD_KEY_CUST_RISK_LEVEL:"CUST_RISK_LEVEL",
        GOAL_LOCAL_FIELD_KEY_SKIP_RISK_LEVEL_IND:"SKIP_RISK_LEVEL_IND",
        PARAM_REMOVE_SELECTED_PRODUCTS:"removeSelectedProducts",
        MAX_ALLOWABLE_PRODUCTSKEY:20,
        WPC_PROD_TYPE_CDE_INS:"INS",
        PRODUCT_ALTERNATIVE_ATTRIBUTE_RISK : "RISK",
        PRODUCT_ALTERNATIVE_ATTRIBUTE_PRODUCT_NAME:"PRD_NAME",
        PRODUCT_ALTERNATIVE_ATTRIBUTE_PRODUCT_TYPE:"PRD_TYPE",
        

}