export const insuranceQuoteConfig={
        IQ_TIMEZONE:'GMT+8',
        EXPIRY_DATE_SYS_FORMAT:'yyyy-MM-dd',
        EXPIRY_DATE_DISPLAY_FORMAT:'dd/mm/yyyy',
        insuranceQuoteItems:'IQ_COVERAGE_TYPE,IQ_FREQUENCY_TYPE',
        IQ_COVERAGE_TYPE:'IQ_COVERAGE_TYPE_YEAR,IQ_COVERAGE_TYPE_MONTH',
        IQ_FREQUENCY_TYPE:'IQ_FREQUENCY_TYPE_YEARLY,IQ_FREQUENCY_TYPE_HALF_YEARLY,IQ_FREQUENCY_TYPE_QUARTERLY,IQ_FREQUENCY_TYPE_MONTHLY,IQ_FREQUENCY_TYPE_SINGLE',
        BASE_CURRENCY:'USD',
        SHOW_COVERAGE_PERIOD:false,
        SHOW_EXPIRY_DATE_TIME:false,
        PRODUCT_KEY_LIST:'prodName,ageCalType',
        SHOW_POLICY_EFFECTIVE_DATE:true,
        SHOW_PAYMENT_TERM:true,
        SHOW_POLICY_TERM:true
}   