const lifeProtectionGoalBean={
         adjustedMonthlyExpenseAmount :0,
         adjustedMonthlyExpenseCurrencyCode :'',
         adjustedMonthlyIncomeAmount :0,
		 adjustedMonthlyIncomeCurrencyCode :'',
         calculatedRiskCapacityLevelNumber :'',
         coveragExistingCITotalAmount :0,
         coveragExistingCITotalCurrencyCode :'' ,
		 coverageAge :0,
		 coverageExistingIncomeBenefitsTotalAmount :0,
		 coverageExistingIncomeBenefitsTotalCurrencyCode :'',
		 coverageLifeInsuranceTotalAmount :'',
		 coverageLifeInsuranceTotalCurrencyCode :'',
		 coveragePeriodIndicator :'Y',
		 currentAge :0,
		 debtRepaymentSimulatePercent :100,
		 financialGoalArrangement :{ applyInflationIndicator : 'Y' , currencyCode :'' , inflationRate :0, spendingCountry :''  },
		 fundInvestmentSavingSimulatePercent :100,
		 goalCostCoverAmount :0,
		 goalCostCoverCurrencyCode :'',
		 goalDescription :'Protection Planning' ,
		 goalForNeed : "" ,
		 goalTypeCode : 'INS_JOURNEY' ,
		 goalYearCount :0,
		 incomeMonthlyAmount :0,
		 incomeMonthlyCurrencyCode :'',
		 incomeRetainSimulatePercent :100,
		 investmentTimeHorizon :0,
		 mortgagesAndDebtsMonthlyRepaymentAmount :0,
		 mortgagesAndDebtsMonthlyRepaymentCurrencyCode : '',
		 mortgagesAndDebtsOutstandingAmount :0,
		 mortgagesAndDebtsOutstandingCurrencyCode :''  ,					                        		  
		 numberOfDependents :0,
		 personalIncomeGrowthRate :0,
		 planForCustomerIndicator : 'Y' ,	
		 protectionNeedType :'' ,
		 returnRate :0,
		 returnRateTypeCode : 'NOML' ,
		 riskLevelNumber :'',
		 riskToleranceLevel :'',
		 savingInvestmentAmount :0,
		 savingInvestmentCurrencyCode :''  ,
		 simulateSegmentIndicator : 'I' ,
		 skipRiskProfilingIndicator : 'N' ,
		 stateBenefitsMonthlyAmount :0,
		 stateBenefitsMonthlyCurrencyCode : '' ,
		 stateBenefitsOfCIAmount :0,
		 stateBenefitsOfCICurrencyCode :  '',
		 stateBenefitsOfDeadAmount :0,
		 stateBenefitsOfDeadCurrencyCode :  ''
}
export default lifeProtectionGoalBean;