export default getSearchFormBean=>{

let  searchFormBean ={
    underlyingInvestmentIndex:null,
    productCode:null,
    productCode2:null,
    productCode3:null,
    productCode4:null,
    productCode5:null,
    extProductCodeShow:null,
    productName:null,
    hsbcHighlight:[],
    suitableProductOnly:[],
    searched:false,
    showSuitableProds:false,
    shortlistProductOnly:[],
    searchCountMap:{},
    isSearchClick:false,
    noChangePiqAndAskList:[],
    selectedInsType:[],
    selectedInsContributePeriod:null,
    otherInsTypeText:null,
    goalTypeCode:null,
    riskLevelKeys:[],
    riskLevelIndex:null,
    timeToMaturity:{
        selectedVal:[],
        optionList:[
            {
             key:null,
             value:null   
            }
        ]
    },
    underlyingInvestment:{
         selectedVal:[],
         optionList:[
            {
             key:null,
             value:null   
            }
        ]
    },
    market:{
         selectedVal:[],
         optionList:[
            {
             key:null,
             value:null   
            }
        ]
    },
    currency:{
         selectedVal:[],
         optionList:[
            {
             key:null,
             value:null   
            }
        ]
    },
    characteristics:{
         selectedVal:[],
         optionList:[
            {
             key:null,
             value:null   
            }
        ]
    },
    minimumInvestmentAmount:{
         selectedVal:[],
         optionList:[
            {
             key:null,
             value:null   
            }
        ]
    },
    onshoreOffshore:{
         selectedVal:[],
         optionList:[
            {
             key:null,
             value:null   
            }
        ]
    },
    assetClass:{
         selectedVal:[],
         optionList:[
            {
             key:null,
             value:null   
            }
        ]
    },
    productType:{
         selectedVal:[],
         optionList:[
            {
             key:null,
             value:null   
            }
        ]
    }
};
return searchFormBean;
}