export const customerInfo = {
 
educationLevel_F:'Completed Form 3',
educationLevel_S:'Completed Secondary',
educationLevel_M:'Post Secondary / Diploma',
educationLevel_U:'University or above',
educationLevel_X:'Below Form 3',


occupation_01:'PROFESSIONAL/SENIOR ADMINISTRATIVE',
occupation_02:'ADMINISTRATIVE/EXECUTIVE',
occupation_03:'CLERICAL',
occupation_04:'SKILLED MANUAL',
occupation_05:'UNSKILLED MANUAL',
occupation_06:'AGRICULTURAL',
occupation_07:'NOT WORKING - STUDENT',
occupation_08:'NOT WORKING - ILL OR INJURED (LONG TERM)',
occupation_09:'NOT WORKING - HOUSEWIFE',
occupation_10:'NOT WORKING - RETIRED',
occupation_11:'SELF-EMPLOYED',
occupation_12:'TEACHER',
occupation_13:'ARMED FORCES',
occupation_14:'POLICE',
occupation_15:'UNEMPLOYED',
occupation_16:'OTHER',
occupation_18:'DOCTOR',
occupation_19:'LAWYER',

occupation_24111:'Accountant(Certified/Chartered)',
occupation_28101:'Airline Captain/Pilot',
occupation_51111:'Airline Hostess/Steward',
occupation_21411:'Architect',
occupation_99301:'Army/Military Services',
occupation_51231:'Bar and Club Tender',
occupation_51411:'Beautician/Hair Stylist',
occupation_83001:'Broadcasting/TV/Movie/Theatre Worker',
occupation_34164:'Buyer/Merchandiser',
occupation_42111:'Cashier',
occupation_51222:'Chef/Cook/Baker',
occupation_91611:'Cleaner/Cleaning Worker',
occupation_24601:'Clergy/Monk/Nun',
occupation_49901:'Clerk',
occupation_51491:'Club Waitress/Hostess',
occupation_31191:'Construction Foreman/Supervisor/Inspector',
occupation_71211:'Construction/Decoration Worker',
occupation_49902:'Customer Service Officer',
occupation_34711:'Designer',
occupation_22221:'Dentist',
occupation_22211:'Doctor',
occupation_91312:'Domestic Helper/Amah',
occupation_83201:'Driver',
occupation_24514:'Editor/Writer/Author',
occupation_21492:'Engineer',
occupation_34741:'Entertainer/Musician/Model/Artist/Sportsman',
occupation_38101:'Factory Supervisor/Foreman',
occupation_69901:'Farmer/Fisher/Agricultural Worker',
occupation_12201:'Financial Controller',
occupation_51611:'Fireman/Fire Service Officer',
occupation_39901:'General Executive/Officer',
occupation_79901:'General Industrial/Production Worker',
occupation_51692:'Guard/Watchman/Security',
occupation_91111:'Hawker',
occupation_51212:'Hotel Worker',
occupation_51631:'Immigration Services Officer',
occupation_34381:'Inland Revenue Officer/Inspector',
occupation_34121:'Insurance Agent/Broker/Financial Planner',
occupation_24193:'Insurance Executive/Underwriter',
occupation_34112:'Investment Broker/Dealer/Analyst',
occupation_24194:'Investment/Fund Manager',
occupation_31203:'IT Professional',
occupation_34281:'Journalist/Reporter',
occupation_24203:'Lawyer/Barrister/Solicitor/Magistrates',
occupation_23101:'Lecturer',
occupation_28401:'Management Consultant',
occupation_29902:'Management/Middle Management/Consuls',
occupation_52302:'Market Worker',
occupation_34163:'Merchant/Businessman',
occupation_32301:'Nurse',
occupation_22293:'Other Medical Professionals',
occupation_49904:'Other Office Workers',
occupation_29905:'Other Professional Jobs',
occupation_39903:'Other Semi-Professional Jobs',
occupation_59902:'Other Service Workers',
occupation_34714:'Photographer',
occupation_51621:'Police Officer',
occupation_11101:'Politician/Ambassador/Consuls-General',
occupation_41423:'Postman',
occupation_23401:'Principal',
occupation_51632:'Prison/Correctional Services Officer',
occupation_12291:'Professor',
occupation_34132:'Property Agent',
occupation_51492:'Public Relations(PR)',
occupation_38201:'Restaurant Manager',
occupation_51233:'Restaurant Waiter/Waitress/Worker',
occupation_59901:'Sales',
occupation_24133:'Sales Manager/Director',
occupation_83401:'Sailor/Seaman',
occupation_41151:'Secretary/Receptionist',
occupation_12102:'Senior Management',
occupation_38301:'Shop Manager',
occupation_79902:'Skilled/Semi-Skilled Worker/Tradesman',
occupation_34601:'Social Worker',
occupation_11201:'Sr. Govt Officials/Sr. Judicial Officials',
occupation_21493:'Surveyor',
occupation_23202:'Teacher',
occupation_31103:'Technician',
occupation_12101:'Top Management (e.g.CEO)',
occupation_51131:'Tourist Guide',
occupation_83501:'Traffic Warden',
occupation_93301:'Transport Worker',
occupation_34141:'Travel/Freight Agent',
occupation_99902:'Not Currently Employed',
occupation_99901:'Not Applicable',

employ_status_S:'',
employ_status_E:'',
employ_status_G:'Student',
employ_status_H:'Housewife',
employ_status_P:'Retired',
employ_status_K:'',
employ_status_U:'Not currency employed',

AD:'Andorra',
AE:'United Arab Emirates',
AF:'Afghanistan',
AG:'Antigua & Barbuda',
AI:'Anguilla',
AL:'Albania',
AM:'Armenia',
AN:'NETHERLAND ANTILLES',
AO:'Angola',
AQ:'Antarctica',
AR:'Argentina',
AS:'American Samoa',
AT:'Austria',
AU:'Australia',
AW:'Aruba',
AX:'Aland Islands',
AZ:'Azerbaijan',
BA:'Bosnia-Herzegovina',
BB:'Barbados',
BD:'Bangladesh',
BE:'BELGIUM',
BF:'Burkina Faso',
BG:'Bulgaria',
BH:'Bahrain',
BI:'Burundi',
BJ:'Benin',
BM:'Bermuda',
BN:'Brunei Darussalam',
BO:'Bolivia',
BR:'Brazil',
BS:'Bahamas',
BT:'Bhutan',
BV:'Bouvet Island',
BW:'Botswana',
BY:'Belarus',
BZ:'Belize',
CA:'Canada',
CC:'Cocos Islands',
CD:'Congo,The Demo Rep',
CF:'Central African Repu',
CG:"Congo People's Rep",
CH:'Switzerland',
CI:"Cote D'ivoire",
CK:'Cook Islands',
CL:'Chile',
CM:'Cameroon',
CN:'China',
CO:'Colombia',
CR:'Costa Rica',
CS:'Serbia & Montenegro',
CU:'Cuba',
CV:'Cape Verde',
CX:'Christmas Island',
CY:'Cyprus',
CZ:'Czech Republic',
DE:'Germany,Federal Rep',
DJ:'Djibouti',
DK:'Denmark',
DM:'Dominica',
DO:'Dominican Republic',
DZ:'Algeria',
EC:'Ecuador',
EE:'Estonia',
EG:'Egypt',
EH:'Western Sahara',
EO:'INTL ORGANISATION (EU)',
ER:'Eritrea',
ES:'Spain',
ET:'Ethiopia',
EU:'THE EUROPEAN UNION',
FI:'Finland',
FJ:'Fiji',
FK:'Falkland IS',
FM:'Micronesia,Fed Stat',
FO:'Faroe Islands',
FR:'France',
FX:'FRANCE,METROPOLITAN',
GA:'Gabon',
GB:'UK',
GD:'Grenada',
GE:'Georgia',
GF:'French Guiana',
GG:'Guernsey,Channel IS',
GH:'Ghana',
GI:'Gibraltar',
GL:'Greenland',
GM:'Gambia',
GN:'Guinea',
GP:'Guadeloupe',
GQ:'Equatorial Guinea',
GR:'Greece',
GS:'S Georgia & Sandwich',
GT:'Guatemala',
GU:'Guam',
GW:'Guinea-Bissau',
GY:'Guyana',
HK:'Hong Kong',
HM:'Heard & Mcdonald IS',
HN:'Honduras',
HR:'Croatia',
HT:'Haiti',
HU:'Hungary',
ID:'Indonesia',
IE:'Irish Republic',
IL:'Israel',
IM:'Isle of Man',
IN:'India',
IO:'Brit Ind Ocean Terr',
IQ:'Iraq',
IR:'Iran',
IS:'Iceland',
IT:'Italy',
JE:'Jersey,Channel IS',
JM:'Jamaica',
JO:'Jordan',
JP:'Japan',
KE:'Kenya',
KG:'Kyrgyzstan',
KH:'Cambodia',
KI:'Kiribati',
KM:'Comoros',
KN:'St Kitts & Nevis',
KP:'Korea,Democratic Pep',
KR:'Korea,Republic Of',
KW:'Kuwait',
KY:'Cayman Islands',
KZ:'Kazakhstan',
LA:"Lao People's Democra",
LB:'Lebanon',
LC:'Saint Lucia',
LI:'Liechtenstein',
LK:'Sri Lanka',
LR:'Liberia',
LS:'Lesotho',
LT:'Lithuania',
LU:'Luxembourg',
LV:'Latvia',
LY:'Libya',
MA:'Morocco',
MC:'Monaco',
MD:'Moldova,Republic Of',
ME:'Montenegro,Republic Of',
MG:'Madagascar',
MH:'Marshall Islands',
MK:'Macedonia',
ML:'Mali',
MM:'Myanmar',
MN:'Mongolia',
MO:'Macau',
MP:'Northern Mariana IS',
MQ:'Martinique',
MR:'Mauritania',
MS:'Montserrat',
MT:'Malta',
MU:'Mauritius',
MV:'Maldives',
MW:'Malawi',
MX:'Mexico',
MY:'Malaysia',
MZ:'Mozambique',
NA:'Namibia',
NC:'New Caledonia',
NE:'Niger',
NF:'Norfolk Islands',
NG:'Nigeria',
NI:'Nicaragua',
NL:'Netherlands',
NO:'Norway',
NP:'Nepal',
NR:'Nauru',
NU:'Niue',
NZ:'New Zealand',
OI:'OFFSHORE ISLANDS',
OM:'Oman',
OO:'INTL ORG (OTH NON-EU)',
PA:'Panama',
PE:'Peru',
PF:'French Polynesia',
PG:'Papua New Guinea',
PH:'Philippines',
PK:'Pakistan',
PL:'Poland',
PM:'St Pierre & Miquelon',
PN:'Pitcairn',
PR:'Puerto Rico',
PS:'Palestinian Terr Occ',
PT:'Portugal',
PW:'Palau',
PY:'Paraguay',
PZ:'PANAMA CANAL ZONE',
QA:'Qatar',
RE:'Reunion',
RO:'Romania',
RS:'Serbia,Republic Of',
RU:'Russian Federation',
RW:'Rwanda',
SA:'Saudi Arabia',
SB:'Solomon Islands',
SC:'Seychelles',
SD:'Sudan',
SE:'Sweden',
SG:'Singapore',
SH:'St. Helena',
SI:'Slovenia',
SJ:'Svalbard & JAN MA IS',
SK:'Slovakia',
SL:'Sierra Leone',
SM:'San Marino',
SN:'Senegal',
SO:'Somali,Democratic Re',
SR:'Surinam,Republic Of',
ST:'Sao Tome & Principe',
SV:'El Salvador',
SY:'Syrian Arab Republic',
SZ:'Swaziland',
TC:'Turks & Caicos Islan',
TD:'Chad',
TF:'French South Terr',
TG:'Togo',
TH:'Thailand',
TJ:'Tajikistan',
TK:'Tokelau',
TL:'Timor Leste',
TM:'Turkmenistan',
TN:'Tunisia',
TO:'Tonga',
TP:'EAST TIMOR',
TR:'Turkey',
TT:'Trinidad and Tobago',
TV:'Tuvalu',
TW:'Taiwan',
TZ:'Tanzania',
UA:'Ukraine',
UG:'Uganda',
UM:'US Minor Out Islands',
US:'United States',
UY:'Uruguay',
UZ:'Uzbekistan',
VA:'Vatican City State',
VC:'St Vincent & the Gre',
VE:'Venezuela',
VG:'Virgin Islands UK',
VI:'Virgin Islands USA',
VN:'Vietnam',
VU:'Vanuatu',
WB:'WEST BANK - PALESTINE',
WF:'Wallis & Futuna IS',
WS:'Samoa',
YE:'Yemen',
YT:'Mayotte',
YU:'YUGOSLAVIA',
ZA:'South Africa',
ZM:'Zambia',
ZR:'ZAIRE',
ZW:'Zimbabwe,ZIMBABWE',
ZZ:'UNDEFINED',

UK:'UNITED KINGDOM',
BEBBelgium:'',
BL:'Saint Barthelemy',
BQ:'Bonaire,St E & Saba',
CW:'Curacao',
MF:'Saint Martin',
SS:'South Sudan',
SX:'St Maarten',
TI:'Tahiti',
XK:'Kosovo',
M1:'Middle East'
}