export default {
    '4':'Warning Message!',
    '8':'validation Error!',
    '16':'Service is temporarily unavailable. Please try again later (Fatal Error).',
    '500':'Service is temporarily unavailable. Please retry later.',
    '404':'Host System is temporarily unavailable.',
    '999':'Service is temporarily unavailable. Please try again later (Fatal Error) {0}.',
    '0':'success',
    'CONFIRM':'confirm successful',
    'INFORM':'inform',
    "TIMEOUT":"Message {0} is timeout.",
    "HTTP404":"Message {0} is temporarily unavailable.",
    "HTTP500":"Message {0} get Internal Error.",
    //QAS
    "QAS0001":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0002":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0003":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0004":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0005":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0006":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0007":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0008":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0009":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0010":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0011":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0012":"Please duly complete this section to further proceed [System code: {1}].",
    "QAS0013":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0014":"Please fully fill the questionnaire Error Code QAS0014.",
    "QAS0015":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0016":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0017":"Some questions remain unanswered. Please duly complete this section to further proceed [System code: {1}].",
    "QAS0018":"Only single answer is allowed in a certain questions. Please review your input [System code: {1}].",
    "QAS0019":"Please provide your input in the appropriate free text field [System code: {1}].",
    "QAS0020":"Some questions remain unanswered. Please duly complete this section to further proceed [System code: {1}].",
    "QAS0021":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0022":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0023":"You have chosen to record a risk tolerance that is higher than your existing recorded risk tolerance. Please specify the cause of this change [System code: {1}].",
    "QAS0024":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0025":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "QAS0026":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "QAS0027":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "CUS0001":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "CUS0002":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "CUS0003":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0100":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0102":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0103":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0104":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0105":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0106":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "CUS0100":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0107":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",
    "QAS0108":"Service is temporarily unavailable. Please call [contact details] for assistance or retry later [System code: {1}].",	
    "QAE0001":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "QAS0028":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "QAS0028_1":"Input Error - Question 1 Missing record update reason for changing to lower answers.[System code: {1}]",
    "QAS0028_2":"Input Error - Question 2 Missing record update reason for changing to lower answers.[System code: {1}]",
    "QAS0028_3a":"Input Error - Question 3a Missing record update reason for changing to lower answers.[System code: {1}]",
    "QAS0028_3b":"Input Error - Question 3b Missing record update reason for changing to lower answers.[System code: {1}]",
    "QAS0028_3c":"Input Error - Question 3c Missing record update reason for changing to lower answers.[System code: {1}]",
    "QAS0109":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "QAS0110":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "QAS0111":"Service is temporarily unavailable. Please retry later. [System code: {1}]",

    //FPS
    "SYS0001":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"SYS0002":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"SYS0003":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"SYS0004":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0001":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0002":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0003":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0004":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0005":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0006":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0007":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0008":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0009":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0010":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0011":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0012":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0013":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0014":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0015":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0016":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0017":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0018":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0019":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0020":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0021":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0022":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0023":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0024":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0025":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0026":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0027":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0028":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0029":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0030":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0031":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0032":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0033":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0034":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0035":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0036":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0037":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0038":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0049":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0050":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0051":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0052":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0053":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0054":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0055":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0056":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0057":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0058":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0059":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VMD0061":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0001":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0002":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0003":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0004":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0005":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0006":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0007":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0008":"",
"VCV0009":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0010":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0011":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0012":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0013":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0014":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0015":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VCV0016":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VLD0001":"Indicated retirement age is greater than life expectancy. Please review your input [System code: {1}].",
"VLD0002":"Current age is greater than desired retirement age. Please review your input,or if you already retired,please select \"Retirement Planning - Living in Retirement\" goal [System code: {1}].",
"VLD0003":"Current age is greater than life expectancy. Please review your input [System code: {1}].",
"VLD0004":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"VLD0005":"Income from savings and investments should form part of your total income and hence should not be greater in value compared to your total income [System code: {1}].",
"VLD0006":"Income from savings and investments is generated from your available funds and hence should not be greater in value compared to available funds [System code: {1}].",
"VLD0007":"You can only draw a lump sum from your stated available funds and hence should not be greater in value compared to available funds [System code: {1}].",
"VLD0008":"You can only draw an amount from your property that is up to the value of your property [System code: {1}].",
"VLD0009":"The education starting year of this goal is earlier than the current year which is not allowed. Please make appropriate adjustment. [System code: {1}]",
"VLD0011":"The education starting year of this goal is earlier than the current year which is not allowed. Please make appropriate adjustment. [System code: {1}]",
"ASY0001":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
"ATN0001":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"ATN0002":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"ATN0003":"Login unsuccessful[/br][/br]The password you have entered is incorrect. Please check that you have provided us with the correct email address and password and try again [System code: {1}].",
"ATN0004":"Login unsuccessful[/br][/br]The password you have entered is incorrect. Please check that you have provided us with the correct email address and password and try again [System code: {1}].",
"ATN0005":"Login unsuccessful[/br][/br]The password you have entered is incorrect. Please check that you have provided us with the correct email address and password and try again [System code: {1}].",
"ATN0006":"Password reset unsuccessful[/br][/br]Your responses do not match with our records. Please try again [System code: {1}].",
"ATN0007":"Password reset unsuccessful[/br][/br]Your responses do not match with our records. Please try again [System code: {1}].",
"ATN0008":"Password reset unsuccessful[/br][/br]Your responses do not match with our records. Please try again [System code: {1}].",
"ATN0009":"Password reset unsuccessful[/br][/br]Your responses do not match with our records. Please try again [System code: {1}].",
"ATN0010":"Password reset unsuccessful[/br][/br]Your responses do not match with our records. Please try again [System code: {1}].",
"ATN0011":"Invalid maintenance code [System code: {1}].",
"ATN0012":"Invalid email format. Please check and try again [System code: {1}].",
"ATN0013":"You have not provided an email address. Please check and try again [System code: {1}].",
"ATN0014":"You have not input your password. Please check and try again [System code: {1}].",
"ATN0015":"You have not input a new password. Please check and try again [System code: {1}].",
"ATN0016":"At least 3 security questions should be answered. Please check and try again [System code: {1}].",
"ATN0017":"At least 3 security questions should be answered. Please check and try again [System code: {1}].",
"ATN0018":"Service is temporarily unavailable. Please retry later [System code: {1}].",
"ATN0019":"At least 3 different security questions should be selected. Please check and try again [System code: {1}].",
"ATN0020":"The phone number that you have provided does not match with our records. Please check and try again [System code: {1}].",
    "ATN0021":"Please wait while we are re-directing to the account activation page to proceed with registration [System code: {1}].",
    "ATN0022":"You have entered an incorrect activation code. Please check and try again [System code: {1}].",
    "ATN0023":"Goal Planner user account is already synchronised [System code: {1}].",
    "ATN0024":"This email address is already synchronised to a Goal Planner user account [System code: {1}].",
    "ATN0025":"Activation code has expired. Please retry [System code: {1}].",
    "ATN0026":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "ATN0027":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "ATN0028":"This email address is already synchronised to another Goal Planner user account [System code: {1}].",
    "ATN0029":"No ID number on user''s registration records. ID type and number is required to proceed with link-up. Please advise customer to update registration information online [System code: {1}].",
    "ATN0030":"Identity verification unsuccessful[/br][/br]ID type and number does not match our records. Please check and try again [System code: {1}].",
    "ATN0031":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0001":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0002":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0003":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0004":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0005":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0006":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0007":"The affordability ratio/ aggregated affordability ratio is unavailable. Please review your input in customer''s financial profile (and make sure customer''s disposable income > 0). If the issue persists,you may 	  choose to calculate & verify affordability manually or contact support hotline [System code: {1}].",
    "FPS0008":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0009":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0010":"Rates are not available. Please try again later [System code: {1}].",
    "FPS0012":"Number of products selected exceeds the capacity supported by the system [System code: {1}].",
    "FPS0013":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0014":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0015":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0016":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0017":"Package mix mip eligible [System code: {1}].",
    "FPS0018":"The same goal description already exists in record,please click \"Revise Goal description\" and give a unique description to this goal [System code: {1}].",
    "FPS0019":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0020":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0021":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0022":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0023":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0024":"The asset concentration ratio/ aggregated asset concentration ratio is unavailable. Please review your input in customer''s financial profile (and make sure customer''s liquid assets > 0). If the issue persists,you may choose to calculate & verify asset concentration manually or contact support hotline [System code: {1}].",
    "FPS0025":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0026":"Before clicking \"Confirm\",please get the quotation from IPS and then click \"Add to Shopping Cart\" [System code: {1}].",
    "FPS0027":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0028":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0029":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0030":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0031":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0032":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0033":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0034":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0035":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0036":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0037":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0038":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0039":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0040":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0041":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0042":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0043":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0044":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0045":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0046":"",
    "FPS0047":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0048":"Please enter a unique description to this goal [System code: {1}].",
    "FPS0049":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0050":"Asset Concentration cannot be calculated. Please calculate manually to check for suitability [System code: {1}].",
    "FPS0051":"",
    "FPS0052":"",
    "FPS0053":"",
    "FPS0054":"",
    "FPS0055":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0056":"Please note that Private placement product(s) was/were selected previously. Please check whether the product(s) is/are suitable to customer [System code: {1}].",
    "FPS0057":"Please check whether customer has signed IISP document for any Investment products to be recommended. If so,please select \"Revise this plan\" to update record in Financial Situation page [System code: {1}].",
    "FPS0058":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0059":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0060":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0061":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0062":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0063":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0064":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0065":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0066":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0067":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "FPS0068":"Staff eligibility cannot be identified. Please ensure staff can proceed with the product solutions below [System code: {1}].",
    "FPS0069":"Customer has not signed the consent form / declaration form for receiving Investment product information. Please check whether customer is interested in Investment product and update record accordingly [System code: {1}].",
    "FPS0070":"Initial amount is too much more than customer''s net worth. Please check [System code: {1}].",
    "FPS0071":"Monthly amount is too much more than customer''s disposable income. Please check [System code: {1}].",
    "FPS0072":"Asset Concentration cannot be calculated. Please calculate manually to check for suitability [System code: {1}].",
    "FPS0073":"Asset Concentration cannot be calculated. Please calculate manually to check for suitability [System code: {1}].",
    "FPS0074":"Customer''s KnE is temporarily unavailable. Please ensure customer has relevant KnE before proceed [System code: {1}].",
    "FPS0075":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0076":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0078":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0079":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0080":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0081":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0082":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0083":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0084":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0085":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0086":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0087":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0088":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0089":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0090":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0091":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0092":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0093":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0094":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0095":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0096":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0097":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0098":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0099":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0100":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0101":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0102":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0296":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "OBS0000":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "FPS0297":"There is contribution period mismatch and it cannot be proceed. ",
    "FPS0298":"Please be aware that the Financial Health Check details are more updated than the financial profile captured in this page.",
    "FPS0303":"You can prefill this section with Financial Health Check details.",
    "FPS0307":"Please be reminded to explain one extra product that can fulfill at least one of the customer's objective(s) as an alternative insurance option (except no eligible insurance product). Rider plan could be an alternative insurance option if no eligible product available.",
    "FPS2013":"Insurance product must be discussed, please check.",
    "FPSBJ0001":"Failed to run FPS batch job,please contact WMD_FPS team [System code: {1}].",
    "FPSBJ0002":"Failed to run FPS batch job,please contact WMD_FPS team [System code: {1}].",
    "FPSBJ0003":"Failed to run FPS batch job,please contact WMD_FPS team [System code: {1}].",
    "FPSBJ0004":"Failed to run FPS batch job,please contact WMD_FPS team [System code: {1}].",
    "FPSBJT001":"Failed to transfer interface file to CDGW for $entity [System code: {1}].",
    "FPSCT0001":"File transfer failure,please contact FPS support [System code: {1}].",
    "FPSHS9999":"Failed to run FPS batch job,please contact WMD_FPS team [System code: {1}].",
    "CAL0001":"Service is temporarily unavailable. Please retry later [System code: {1}]. ",
    "CAL0002":"Service is temporarily unavailable. Please retry later [System code: {1}]. ",
    "CAL0003":"Service is temporarily unavailable. Please retry later [System code: {1}]. ",
    "CAL0004":"Service is temporarily unavailable. Please retry later [System code: {1}]. ",
    "CAL0005":"Service is temporarily unavailable. Please retry later [System code: {1}]. ",
    "CAL0006":"Service is temporarily unavailable. Please retry later [System code: {1}]. ",
    "CAL0007":"Zero disposable income [System code: {1}].",
    "CAL0008":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "CAL0009":"Please input either initial amount or monthly amount to proceeed [System code: {1}].",
    "CAL0010":"Total Initial amount / Total monthly amount varies from the desired amount from Simulator by 5% and 10% respectively. Please ensure the input is according to customer''s need [System code: {1}].",
    "CAL0011":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "CAL0012":"Not able to calculate the portfolio risk [System code: {1}].",
    "CAL0013":"Not able to calculate the portfolio risk [System code: {1}].",
    "CAL0014":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "CAL0015":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "CAL0016":"Not able to calculate the portfolio risk [System code: {1}].",
    "CAL0017":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "CAL0018":"Service is temporarily unavailable. Please retry later.[System code: {1}]",
    "BWC0001":"Portfolio allocation cannot be achieved. Please proceed accordingly [System code: {1}].",
    "QUO0001":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "QUO0002":"[System code: {1}]",
    "QUO0003":"The quote details with the same key (CC,GM,App ID,Quote ID) already exists [System code: {1}].",
    "CFG0001":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "GIP0001":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "ICCM001":"The reason code from ICCM HA is not normal[System code: {1}]",
    "ICCM002":"ICCM template Not Found[System code: {1}]",
    "ICM0001":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "ICM0002":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "HAD0001":"Return when don''t get response message or response message is not incorrect.[System code: {1}]",
    "HAD0002":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "HAD0003":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "HAD0004":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "HAD0005":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "HAD0006":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "HAD0007":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "INV0001":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "RKL0001":"Not able to calculate the portfolio risk [System code: {1}].",
    "RPT0001":"Service is temporarily unavailable. Please retry later. [System code: {1}].",
    "SMT0001":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "SMT0002":"Too much goal num[System code: {1}]",
    "WEC0001":"The reason code from WEC HA is not normal in validate product eligibility[System code: {1}]",
    "WEC0002":"The reason code from WEC HA is not normal in retrieve eligible product list[System code: {1}]",
    "WPC0001":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "WPC0002":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "WPC0003":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "SOLE_ID_INVALID_ERROR" : "System supports only 2 sole customers in joint customer cases.",
    "DEFAULT_REPORTGENERATION_ERROR" : "In progress and please try later.",
    "ERROR_INVALID_PARAM_FOR_JOINT_CIN":"Joint customer id should be passed in by HSBC_OHD_CUSTOMER_ID.",
    "VLD0010":"The education starting year of this goal is earlier than the current year which is not allowed. Please make appropriate adjustment. [System code: {1}]",
    "FPS0103":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0104":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0105":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0106":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0107":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0108":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0109":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0110":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0111":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0112":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0113":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0114":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "VMD0062":"[System code: {1}]",
    "VMD0063":"[System code: {1}]",
    "FPS0115":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0116":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0117":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0118":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0119":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0120":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0121":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0122":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0123":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0124":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0125":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0126":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0200":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0201":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0202":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0204":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0205":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0206":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "SYS0006":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0208":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0207":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0209":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0210":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0211":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0212":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0213":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0214":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0215":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0216":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0217":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0218":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0219":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0220":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0223":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0221":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0222":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0224":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0225":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "FPS0305":"Can't retrieve outstanding insurance premium amount from L400.",  
    "FPS0308":"The L400 service you have requested is temporarily unavailable.  Please try again later. (code: 8LM)",
    "FPS0309":"L400 is out of service hour.", 
    "FPS0310":"The L400 service you have requested is temporarily unavailable.  Please try again later.",
    "FPS0311":"Remarks for conflicting information is missing. To proceed, please input remarks in 'Average monthly expenses in the past 2 years' breakdown section under 'Your Financial Profile' page.",
    "FPS0312":"Remarks for conflicting information is missing. To proceed, please input remarks in 'Assets (excl. self-use property)' breakdown section under 'Your Financial Profile' page.",
    "FPS0313":"Remarks for conflicting information is missing. To proceed, please input remarks in 'Liabilities' breakdown section under 'Your Financial Profile' page.",
    "ILS0001":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0002":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0003":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0004":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0005":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0006":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0007":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0008":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0009":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0010":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0011":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0012":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0013":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0014":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0015":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0016":"Service is temporarily unavailable. Please retry later. [System code: {1}]",
    "ILS0017":"Service is temporarily unavailable. Please retry later. [System code: {1}]",


    "SYS0005":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "SYS0099":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "QASE0001":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "ICCM0001":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "ICCM0002":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "WEC0003":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "WEC0004":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "WEC0005":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "WEC0006":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "WEC0007":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "WEC0008":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "WEC0009":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "WEC0010":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "WEC0112":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "WEC0113":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    "WEC0205":"Service is temporarily unavailable. Please retry later [System code: {1}].",
    //PVC error message
    "PVC0001":"Please propose at least one product with risk rating 3 or below [System code: {1}].",
    "PVC0002":"For customer aged below 75, propose at least one suitable product risk rated 3 or below where appropriate. [/br]For customer aged 75 or above, propose suitable products where appropriate according to prevailing guidelines [System code: {1}].",
    "PVC0003":"High asset concentration in structured product (investment amount is at or above 20% of your total net worth (excluding real estate properties)) is not allowed [System code: {1}].",
    "PVC0004":"High asset concentration (cumulative investment / premium in one of the product categories is higher than 50% of your total assets (excluding real estate properties)) is not allowed [System code: {1}].",
    "PVC0005":"Customer''s declaration on assets and income is not aligned with the earlier inputs.  Please revise accordingly [System code: {1}].",
    "PVC0006":"For customer aged below 75, propose at least one suitable product risk rated 3 or below where appropriate. [/br]For customer aged 75 or above, propose suitable products where appropriate according to prevailing guidelines; otherwise, input ''N/A'' at  'product name' field to proceed. [System code: {1}].",
    "PVC0007":"High asset concentration (investment amount in one or more of the structured product transactions is equal to or higher than 20% of your total assets (excluding real estate properties)) is not allowed [System code: {1}].",
    "PVC0008":"High asset concentration in high yield bond (investment amount is at or above 20% of your total net worth (excluding real estate properties)) is not allowed [System code: {1}].",
    "PVC0009":"WARNING_CODE_PVC_DEFAULT_CONCENTRATION_RISK_EXCEED [System code: {1}].",
    "OCI0001":"Insurance payment term can not be deduced [System code: {1}].",
    "OCI0002":"Please re-do Financial Planning Report (FPR) by Edit Plan due to new regulatory requirement changes. [System code: {1}].",
    "OCI0003":"Please re-do Financial Planning Report (FPR) by Edit Plan due to new regulatory requirement changes. [System code: {1}].",
    "CAL0030":"The investment amount is over the initial amount",
    "CAL0031":"The investment amount is under the initial amount",
    "FPS2101":"The investment amount is over the initial amount without a given reason [System code: {1}].",
    "FPS2102":"The investment amount is under the initial amount without a given reason [System code: {1}].",
    //#goal description validation
    "SIM10007":"Please enter a minimum of one character and up to a maximum of 100 characters before saving the goal name.",
    "SIM10010":"The following characters are not permitted <>'%^?!&. Please enter the goal description again.",
    "FPS2103":"Different retirement ages are being input in different goal, please review.",
    "FPS0304":"Objective mismatch: Insurance policy''s objective does not fulfill customer''s objectives of buying the insurance product.",
    "SYS9999":"Service is temporarily unavailable. Please retry later."
}