export const RISKPROFILEQUEST_INIT = 'RISKPROFILEQUEST_INIT';
export const RISKPROFILEQUEST_INIT1 = 'RISKPROFILEQUEST_INIT1';
export const RISKPROFILEQUESTTEXT_INIT = 'RISKPROFILEQUESTTEXT_INIT';
export const RISKPROFILEQUESTTEXT_UPDATE = 'RISKPROFILEQUESTTEXT_UPDATE';
export const RISKPROFILEQUESTTEXT_GETRESULT = 'RISKPROFILEQUESTTEXT_GETRESULT';
export const RISKPROFILEQUESTTEXT_CAL = 'RISKPROFILEQUESTTEXT_CAL';
export const RISKPROFILEQUESTTEXT_CLEANCULRESULT = 'RISKPROFILEQUESTTEXT_CLEANCULRESULT';
export const RISKPROFILEQUESTTEXT_GETSTAFFINFO = 'RISKPROFILEQUESTTEXT_GETSTAFFINFO';
export const RISKPROFILEQUESTTEXT_GETSTAFFINFO_DONE = 'RISKPROFILEQUESTTEXT_GETSTAFFINFO_DONE';
export const RISKPROFILEQUESTTEXT_SETBACK = 'RISKPROFILEQUESTTEXT_SETBACK';

export const initRiskProfileQuestData=(rtqParams)=>({
    type: RISKPROFILEQUEST_INIT,
    rtqParams
})

export const initRiskProfileQuestTextData=(rpqTextParams)=>({
    type: RISKPROFILEQUESTTEXT_INIT,
    rpqTextParams
})

export const getRiskProfileResult=(rpqRankParams)=>({
    type: RISKPROFILEQUESTTEXT_GETRESULT,
    rpqRankParams
})

export const setBack=()=>({
    type: RISKPROFILEQUESTTEXT_SETBACK,
})

export const cleanCulResult=()=>({
    type: RISKPROFILEQUESTTEXT_CLEANCULRESULT,
})

export const getStaffInformation=(staffId)=>({
    type: RISKPROFILEQUESTTEXT_GETSTAFFINFO,
    staffId
})



