export default{
        RETRIEVEINVOLVEDPARTYDETAILSINDIVIDUAL:'retrieveInvolvedPartyDetailsIndividual',
		RETRIEVESOLECUSTOMERID:'retrieveSoleCustomerId',
        RETRIEVECUSTOMERLISTBYKEY:'retrieveCustomerListByKey',
        RECORDACTIVITYAUDITLOG:'recordActivityAuditLog',
        RETRIEVEPRODUCTSEARCHRESULT:'retrieveProductSearchResult',
        RETRIEVEPRODUCTCOUNT:'retrieveProductCount',
        CALCULATERISKCAPACITY:'calculateRiskCapacity',
        CALCULATEAGGREGATEAFFORDABILITYRATIO:'calculateAggregateAffordabilityRatio',
        RETRIEVEGOALSUMMARYLIST:'retrieveGoalSummaryList',
        RETRIEVEFINANCIALSITUATIONDATA:'retrieveFinancialSituationData',
        RECORDFINANCIALSITUATIONDATA:'recordFinancialSituationData',
        RETRIEVECUSTOMERGENERALGOAL:'retrieveCustomerGeneralGoal',
        RECORDCUSTOMERGENERALGOAL:'recordCustomerGeneralGoal',
        RETRIEVEGOALSOLUTIONDETAIL:'retrieveGoalSolutionDetail',
        RECORDGOALSOLUTIONDETAIL:'recordGoalSolutionDetail',
        RETRIEVECUSTOMERFINANCIALINFO:'retrieveCustomerFinancialInfo',
        RETRIEVEGOALPLANNERINFO:'retrieveGoalPlannerInfo',
        RECORDGOALPLANNERINFO :'recordGoalPlannerInfo',
        RETRIEVEMEETINGSUMMARYREPORTARCHIVE:'retrieveMeetingSummaryReportArchive',
        MAINTAINGOALTAGGING:'maintainGoalTagging',
        RECORDMEETINGSUMMARYREPORTARCHIVEACK:'recordMeetingSummaryReportArchiveAck',
        RECORDCUSTFINPLANINFO:'recordCustFinPlanInfo',  
        DELETEGOALINFORMATION:'deleteGoalInformation',
        RETRIEVECONTROLADVICEDETAIL:'retrieveControlAdviceDetail',
        MAINTAINMEETINGSUMMARYREPORT:'maintainMeetingSummaryReport',
        RETRIEVEMANAGEDSOLUTIONDETAIL:'retrieveManagedSolutionDetail',
        REVIEWINVESTMENTS:'reviewInvestments',
        RETRIEVEINSURANCEQUOTEDETAILS:'retrieveInsuranceQuoteDetails',
        RECORDINSURANCEQUOTEDETAILS:'recordInsuranceQuoteDetails',
        RECORDQUOTEID:'recordQuoteId',
        RETRIEVEGOALPROJECTION:'retrieveGoalProjection',
        RETRIEVEORDERPLACEMENT:'retrieveOrderPlacement',
        CREATEORDERPLACEMENT:'createOrderPlacement',
        RETRIEVETAXOPTIMIZATIONDETAILS:'retrieveTaxOptimizationDetails',
        RECORDTAXOPTIMIZATIONDETAILS:'recordTaxOptimizationDetails',
        CREATEPLACEHOLDERACCOUNT:'createPlaceholderAccount',
        RETRIEVEFINANCIALGOALQUESTIONNAIRE:'retrieveFinancialGoalQuestionnaire',
        RECORDFINANCIALGOALQUESTIONNAIRE:'recordFinancialGoalQuestionnaire',
        FPSDOWNLOADCONTROLDATA:'fpsDownloadControlData',
        RETRIEVEEXISTINGHOLDINGSCONTRIBUTION:'retrieveExistingHoldingsContribution',
        RECORDEXISTINGHOLDINGSCONTRIBUTION:'recordExistingHoldingsContribution',
        RETRIEVECUSTOMERACCOUNTLIST:'retrieveCustomerAccountList',
        RECORDBASEGOAL:'recordBaseGoal',

        RETRIEVEFINANCIALSITUATIONREFERENCERECORDASSETS:'retrieveFinancialSituationReferenceRecordAssets',
        RETRIEVEFINANCIALSITUATIONREFERENCERECORDEXPENSES:'retrieveFinancialSituationReferenceRecordExpenses',
        RETRIEVEFINANCIALSITUATIONREFERENCERECORDINCOME:'retrieveFinancialSituationReferenceRecordIncome',
        RETRIEVEFINANCIALSITUATIONREFERENCERECORDLIABILITIES:'retrieveFinancialSituationReferenceRecordLiabilities',
        
        ENQUIREFHCSUMMARY:'enquireFhcSummary',
        RETRIEVEFHCDETAIL:'retrieveFhcDetail',
        RETRIEVEBYCURRENCY:'retrieveByCurrency',
        UPDATEFHCRESULT:'updateFhcResult',
        RETRIEVELIFE400INSURANCEDETAIL:'retrieveLife400InsuranceDetail',

        CALCULATEPROTECTIONPLANNING:'calculateProtectionPlanning', 
        RECORDPROTECTIONPLANNING:'recordProtectionPlanning',
        RETRIEVEPROTECTIONPLANNING:'retrieveProtectionPlanning', 
        CALCULATEPLANNINGYOURRETIREMENT:'calculatePlanningYourRetirement',
        RETRIEVEPLANNINGYOURRETIREMENT:'retrievePlanningYourRetirement', 
        RECORDPLANNINGYOURRETIREMENT:'recordPlanningYourRetirement', 
        CALCULATERETIRMENTBENEFITS:'calculateRetirementBenefits',
	CALCULATEGROWINGYOURWEALTH:'calculateGrowingYourWealth',

        CALCULATEEDUCTION:'calculateEducation',
        CALCULATERETIREMENT:'calculateRetirement',
        CALCULATELIFECOVERAGE:'calculateLifeCoverage',
        CALCULATECRITICALILLNESS:'calculateCriticalIllness',
        CALCULATEEDUCTION2:'calculateEducation2',
        CALCULATERETIREMENT2:'calculateRetirement2',
        CALCULATELIFECOVERAGE2:'calculateLifeCoverage2',
        CALCULATECRITICALILLNESS2:'calculateCriticalIllness2',

        ASSETCONCENTRATIONCALCULATIONGETHOLDING:'assetConcentrationCalculationGetHolding',
        FINANCIALSITUATIONREFERENCERECORDSERVICEASSETS:'financialSituationReferenceRecordServiceAssets',
}