
export const MEETINGSUMMY_INIT_IPDETAIL='MEETINGSUMMY_INIT_IPDETAIL';
export const MEETINGSUMMY_INIT_IPDETAIL_UPDATE='MEETINGSUMMY_INIT_IPDETAIL_UPDATE';
export const MEETINFSUMMARY_RETRIEVE_QUESTIONNAIRE_SUMMARY = 'MEETINFSUMMARY_RETRIEVE_QUESTIONNAIRE_SUMMARY';
export const MEETINFSUMMARY_RETRIEVE_QUESTIONNAIRE_SUMMARY_UPDATE = 'MEETINFSUMMARY_RETRIEVE_QUESTIONNAIRE_SUMMARY_UPDATE';
export const MEETINFSUMMARY_RETRIEVE_FNA_DATA = 'MEETINFSUMMARY_RETRIEVE_FNA_DATA';
export const MEETINFSUMMARY_RETRIEVE_FNA_DATA_UPDATE = 'MEETINFSUMMARY_RETRIEVE_FNA_DATA_UPDATE';
export const MEETINFSUMMARY_GOAL_SUMMARY_LIST = 'MEETINFSUMMARY_GOAL_SUMMARY_LIST';
export const MEETINFSUMMARY_GOAL_SUMMARY_LIST_UPDATE = 'MEETINFSUMMARY_GOAL_SUMMARY_LIST_UPDATE';
export const MEETINFSUMMARY_RETRIEVE_GOAL_DETAIL = 'MEETINFSUMMARY_RETRIEVE_GOAL_DETAIL';
export const MEETINFSUMMARY_RETRIEVE_GOAL_DETAIL_UPDATE = 'MEETINFSUMMARY_RETRIEVE_GOAL_DETAIL_UPDATE';


export const initInvolvedPartyDetail=(ipDetailRequest,assetsParams)=>({
    type: MEETINGSUMMY_INIT_IPDETAIL,
    ipDetailRequest:ipDetailRequest,
    assetsParams:assetsParams
})

export const getHistoricalRecords=(rtqHistoricalParams)=>({
    type: MEETINFSUMMARY_RETRIEVE_QUESTIONNAIRE_SUMMARY,
    rtqHistoricalParams
})
export const meetingSummaryFNAData=(fnaParams)=>({
    type: MEETINFSUMMARY_RETRIEVE_FNA_DATA,
    fnaParams
})
export const retrieveGoalList=(params)=>({
    type: MEETINFSUMMARY_GOAL_SUMMARY_LIST,
    params
})
export const retrieveGoalDetail=(params)=>({
    type: MEETINFSUMMARY_RETRIEVE_GOAL_DETAIL,
    params
})



