export const PIQCriterias = [
    {
        code:"RISKCP",
        type:"singleValue",
        option:"auto" //auto means no value
    },{
        code:"INVPERIOD",
        type:"singleValue",
        option:"auto"
    },{
        code:"LIQQUES",
        type:"singleValue",
        option:"auto"
    },{
        code:"CAPPROQUES",
        type:"singleValue",
        option:"auto"
    },{
        code:"AIPI",
        type:"singleValue",
        option:"auto"
    },{
        code:"INV",
        type:"singleValue",
        option:"auto"
    },
    {
        code:"GOALTYPE",
        type:"singleValue",
        option:"auto"
    }
];

export const productCriterias =[
    {
        code:"RISK_LVL_CDE",
        type:"singleValue",
        keyType:"GENL",
        valueType:"OTHER",
        operation:"<=",
        opt:"manual"
    },{
        code:"TERM_REMAIN_DAY_CNT",
        type:"list",
        keyType:"GENL",
        valueType:"REFDAT",
        operation:"RANGE",
        opt:"auto"
    },{
        code:"CCY_PROD_CDE",
        type:"list",
        keyType:"GENL",
        valueType:"REFDAT",
        operation:"=",
        opt:"auto"
    },{
        code:"SUITABLE_PRODUCT_ONLY",
        type:"searchCriteria",
        opt:"auto"
    },{
        code:"SHORTLIST_PRODUCT",
        type:"searchCriteria",
        opt:"auto"
    },{
        code:"MKT_INVST_CDE",
        type:"list",
        keyType:"GENL",
        valueType:"REFDAT",
        operation:"=",
        opt:"auto"
    },{
        code:"PROD_TYPE_CDE",
        type:"list",
        keyType:"GENL",
        valueType:"REFDAT",
        operation:"=",
        opt:"auto"
    },{
        code:"strategy",
        type:"list",
        keyType:"",
        valueType:"",
        operation:"",
        opt:"ignore"
    },{
        code:"FUND_HOUSE_CDE",
        type:"list",
        keyType:"UNTR",
        valueType:"REFDAT",
        operation:"=",
        opt:"auto"
    },{
        code:"ASET_VOLTL_CLASS_MAJR_PRNT_CDE",//asset class
        type:"list",
        keyType:"GENL",
        valueType:"REFDAT",
        operation:"=",
        opt:"auto"
    },{
        code:"ALLOW_SELL_MIP_PROD_IND",
        type:"singleValue",
        keyType:"GENL",
        valueType:"TEXT",
        operation:"=",
        opt:"manual"
    },{
        code:"INCM_HANDL_OPT_CDE",//share class
        type:"list",
        keyType:"UNTR",
        valueType:"REFDAT",
        operation:"=",
        opt:"auto"
    },{
        code:"PROD_NAME",
        type:"singleValue",
        keyType:"GENL",
        valueType:"OTHER",
        operation:"LIKE",
        opt:"manual"
    }
]